##################################
## Script invoked from legdeb.r ##
## fixes legislator names       ##
##################################

# valid for all
speeches$who <- sub.e(" +$" , "", speeches$who) # drop trailing spaces
speeches$who <- sub.e("^ +" , "", speeches$who) # drop heading spaces
speeches$who <- sub.e(" +" , " ", speeches$who) # drop double spaces
speeches$who <- sub.e("[.]$" , "", speeches$who) # drop trailing period
speeches$who <- sub.e("  +" , " ", speeches$who) # drop double+ spaces
speeches$who <-   gsub("Á" , "A", speeches$who)  # drop accented capitals
speeches$who <-   gsub("É" , "E", speeches$who)  # drop accented capitals
speeches$who <-   gsub("Í" , "I", speeches$who)  # drop accented capitals
speeches$who <-   gsub("Ó" , "O", speeches$who)  # drop accented capitals
speeches$who <-   gsub("Ú" , "U", speeches$who)  # drop accented capitals


# legislatura 62 fixes
sel.leg <- which(speeches$leg==62)
if (length(sel.leg) > 0){
    tmp.fix <- speeches # duplicate
    speeches <- speeches[sel.leg,] # subset from manipulation
                                        #
    speeches$who <- gsub.e("El diputado El diputado" , "El diputado", speeches$who)
    speeches$who <- gsub.e("Salador Arellano" , "Salvador Arellano", speeches$who)
    speeches$who <- gsub.e("King de la Rosa" , "King De la Rosa", speeches$who)
    speeches$who <- gsub.e("Raimundo King" , "Raymundo King", speeches$who)
    speeches$who <- gsub.e("Oswaldo Ochoa Gallegos Williams" , "Williams Oswaldo Ochoa Gallegos", speeches$who)
    speeches$who <- gsub.e("Núñez Monreal Magdalena del Socorro" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Micher Camarena" , "Mícher Camarena", speeches$who)
    speeches$who <-   gsub("[YJ]azm[íi]n de los Angeles [Cc]opete Zapot" , "Yazmín de los Angeles Copete Zapot", speeches$who)
    speeches$who <- gsub.e("Zúniga" , "Zúñiga", speeches$who)
    speeches$who <- gsub.e("Zuleyma Hudibro González" , "Zuleyma Huidobro González", speeches$who)
    speeches$who <- gsub.e("William Renan Sosa" , "William Renán Sosa", speeches$who)
    speeches$who <- gsub.e("Víctor Raymundo Nájera" , "Víctor Reymundo Nájera", speeches$who)
    speeches$who <- gsub.e("Rafael González Manrique" , "Rafael González Manríquez", speeches$who)
    speeches$who <- gsub.e("Verónica Beatríz" , "Verónica Beatriz", speeches$who)
    speeches$who <- gsub.e("Jesús Mujica Morga" , "Jesús Mojica Morga", speeches$who)
    speeches$who <- gsub.e("Taya Rellstab" , "Tanya Rellstab", speeches$who)
    speeches$who <- gsub.e("Tanya Rellstab Carreto" , "Tanya Rellstab", speeches$who) # there must be a better way
    speeches$who <- gsub.e("Tanya Rellstab" , "Tanya Rellstab Carreto", speeches$who) # there must be a better way
    speeches$who <- gsub.e("Roxana Luna Portillo" , "Roxana Luna Porquillo", speeches$who)
    speeches$who <- gsub.e("Villareal" , "Villarreal", speeches$who)
    speeches$who <- gsub.e("Mej[ií]a Berdejas?" , "Mejía Berdeja", speeches$who)
    speeches$who <- gsub.e("García Berdeja" , "Mejía Berdeja", speeches$who)
    speeches$who <- gsub.e("Ricardo Avila Monreal" , "Ricardo Monreal Avila", speeches$who)
    speeches$who <- gsub.e("Ricardo Anaya Cortéz" , "Ricardo Anaya Cortés", speeches$who)
    speeches$who <- gsub.e("René Fujiwara Montelongo" , "René Ricardo Fujiwara Montelongo", speeches$who)
    speeches$who <- gsub.e("Regina Vázquez" , "Regina Vázquez Saut", speeches$who)
    speeches$who <- gsub.e("Raquel Jiménez Cerillo" , "Raquel Jiménez Cerrillo", speeches$who)
    speeches$who <- gsub.e("Resendiz" , "Reséndiz", speeches$who)
    speeches$who <- gsub.e("Peña Rocío" , "Peña Recío", speeches$who)
    speeches$who <- gsub.e("Nestor Octavio" , "Néstor Octavio", speeches$who)
    speeches$who <- gsub.e("Meri?lyn Gómez Poz[oa]s" , "Merilyn Gómez Pozos", speeches$who)
    speeches$who <- gsub.e("Mayra Robles Aguirre" , "Mayra Karina Robles Aguirre", speeches$who)
    speeches$who <- gsub.e("Vázquez Villanueva" , "Vásquez Villanueva", speeches$who)
    speeches$who <- gsub.e("Mario Sánchez Ruíz" , "Mario Sánchez Ruiz", speeches$who)
    speeches$who <- gsub.e("María del Rosario Fátima Pariente Gavito" , "María del Rosario de Fátima Pariente Gavito", speeches$who)
    speeches$who <- gsub.e("Carmen Martínez Santillana" , "Carmen Martínez Santillán", speeches$who)
    speeches$who <- gsub.e("Ramírez Díez Gutiérrez" , "Ramírez Diez Gutiérrez", speeches$who)
    speeches$who <- gsub.e("Margarita Elena Tapia Fonllem" , "emm-temporal", speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Elena Tapia Fonllem" , "Margarita Elena Tapia Fonllem", speeches$who)     # there must be a better way
    speeches$who <- gsub.e("Margarita Tapia Fonllem" , "Margarita Elena Tapia Fonllem", speeches$who) # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Margarita Elena Tapia Fonllem" , speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Margarita Elena Tapia Fonllem" , "emm-temporal", speeches$who)       # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Margarita Elena Tapia Fonllem" , speeches$who)       # there must be a better way
    speeches$who <- gsub.e("Manilo Fabio" , "Manlio Fabio", speeches$who)
    speeches$who <- gsub.e("Magdalena Núñez Monreal" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Ma Elena Cano Ayala" , "María Elena Cano Ayala", speeches$who)
    speeches$who <- gsub.e("Luis María Alcalde Luján" , "Luisa María Alcalde Luján", speeches$who)
    speeches$who <- gsub.e("Garfías Gutiérrez" , "Garfias Gutiérrez", speeches$who)
    speeches$who <- gsub.e("Loret.a (?:Ort[íi]z|Ruiz) Ahlf" , "Loretta Ortiz Ahlf", speeches$who)
    speeches$who <- gsub.e("Loreni?a Iveth Valles? Samperio" , "Lorenia Iveth Valles Sampedro", speeches$who)
    speeches$who <- gsub.e("Athie Flores" , "Athié Flores", speeches$who)
    speeches$who <- gsub.e("Julisa Mejía Guajardo" , "Julisa Mejía Guardado", speeches$who)
    speeches$who <- gsub.e("Judith Magdalena Guerrero López" , "Judit Magdalena Guerrero López", speeches$who)
    speeches$who <-   gsub("Juan francisco" , "Juan Francisco", speeches$who)
    speeches$who <- gsub.e("J. Pilar Montenegro Montoya" , "J. Pilar Moreno Montoya", speeches$who)
    speeches$who <- gsub.e("Quiróga" , "Quiroga", speeches$who)
    speeches$who <- gsub.e("José Manzur Quiroga" , "José Sergio Manzur Quiroga", speeches$who)
    speeches$who <- gsub.e("Federico José González Luna Bueno" , "emm-temporal", speeches$who) # there must be a better way
    speeches$who <- gsub.e("José González$" , "José González Morfín", speeches$who)            # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Federico José González Luna Bueno", speeches$who)  # there must be a better way
    speeches$who <- gsub.e("López Candido" , "López Cándido", speeches$who)
    speeches$who <- gsub.e("León Mendivil" , "León Mendívil", speeches$who)
    speeches$who <- gsub.e("Botello Méndez" , "Botello Montes", speeches$who)
    speeches$who <- gsub.e("Jorge Iván Villalobos Sánchez" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Murilla Karam" , "Murillo Karam", speeches$who)
    speeches$who <- gsub.e("Jéssica Salazar" , "Jessica Salazar", speeches$who)
    speeches$who <- gsub.e("Jazmin" , "Jazmín", speeches$who)
    speeches$who <- gsub.e("[JY]azm[ií]n(?: de los Angeles)? Copete Zapot" , "Yazmín de los Angeles Copete Zapot", speeches$who)
    speeches$who <- gsub.e("Héctor Hugo R[eo]ble[dr]o Gordillo" , "Héctor Hugo Roblero Gordillo", speeches$who)
    speeches$who <- gsub.e("Eligio Cuitláhuac González Farías" , "emm-temporal", speeches$who)    # there must be a better way
    speeches$who <- gsub.e("González Farías" , "Eligio Cuitláhuac González Farías", speeches$who) # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Eligio Cuitláhuac González Farías" , speeches$who)    # there must be a better way
    speeches$who <- gsub.e("Gisela Mota Ocampo" , "Gisela Raquel Mota Ocampo", speeches$who)
    speeches$who <- gsub.e("Albarran" , "Albarrán", speeches$who)
    speeches$who <- gsub.e("Cortazar" , "Cortázar", speeches$who)
    speeches$who <- gsub.e("Cárdenas Guizar" , "Cárdenas Guízar", speeches$who)
    speeches$who <- gsub.e("Francisco Alonso Durazo" , "Francisco Alfonso Durazo", speeches$who)
    speeches$who <-   gsub("Francisco Agustín [Aa]rro[yl]l?o Vieye?ra" , "Francisco Agustín Arroyo Vieyra", speeches$who)
    speeches$who <- gsub.e("Francisca Elena Corrales Corrales" , "emm-temporal", speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Francisca Elena Corrales", "Francisca Elena Corrales Corrales", speeches$who) # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Francisca Elena Corrales Corrales" , speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Salgado[(]" , "Salgado", speeches$who)
    speeches$who <- gsub.e("Bibriesca Sahagún" , "Bribiesca Sahagún", speeches$who)
    speeches$who <- gsub.e("Belauzarán" , "Belaunzarán", speeches$who)
    speeches$who <- gsub.e("Fernando Alejandro Larraz[aá]bal (?:Bretón|Betrón)" , "Fernando Alejandro Larrazabal Bretón", speeches$who)
    speeches$who <- gsub.e("Federico González Luna Bueno" , "Federico José González Luna Bueno", speeches$who)
    speeches$who <-   gsub("robledo Leal" , "Robledo Leal", speeches$who)
    speeches$who <- gsub.e("Rom[aá]n Qui[aá]n" , "Román Quian", speeches$who)
    speeches$who <- gsub.e("Dora María Talamante Lemas" , "Dora María Guadalupe Talamante Lemas", speeches$who)
    speeches$who <- gsub.e("Diego Sinhue" , "Diego Sinhué", speeches$who)
    speeches$who <- gsub.e("Barcenas Nieves" , "Bárcenas Nieves", speeches$who)
    speeches$who <- gsub.e("Pérez Tejeda Padilla" , "Pérez Tejada Padilla", speeches$who)
    speeches$who <- gsub.e("Dario Zacarías Capuchino" , "Darío Zacarías Capuchino", speeches$who)
    speeches$who <- gsub.e("Ruíz" , "Ruiz", speeches$who)
    speeches$who <-   gsub("[CD]uarte Or[dt]uño" , "Duarte Ortuño", speeches$who)
    speeches$who <- gsub.e("Carmen Lucia" , "Carmen Lucía", speeches$who)
    speeches$who <- gsub.e("Carlos de Jesús Alejandro" , "Carlos De Jesús Alejandro", speeches$who)
    speeches$who <- gsub.e("Sttefan" , "Steffan", speeches$who)
    speeches$who <- gsub.e("Antonio Altamirano Carol" , "Carol Antonio Altamirano", speeches$who)
    speeches$who <- gsub.e("Amira Griselda" , "Amira Gricelda", speeches$who)
    speeches$who <- gsub.e("Amilcar" , "Amílcar", speeches$who)
    speeches$who <- gsub.e("All?iet Mariana Bautista (?:Bravo|López)" , "Alliet Mariana Bautista Bravo", speeches$who)
    speeches$who <- gsub.e("Alicia Ricalde Magaña" , "Alicia Concepción Ricalde Magaña", speeches$who)
    speeches$who <- gsub.e("Alfonso Montaño" , "Alfonso Inzunza Montaño", speeches$who)
    speeches$who <- gsub.e("Alejandro Carvajal[.] González" , "Alejandro Carbajal González", speeches$who)
    speeches$who <- gsub.e("Aida Fabiola" , "Aída Fabiola", speeches$who)
    speeches$who <- gsub.e("Adolfo Oribe Bellinger" , "Adolfo Orive Bellinger", speeches$who)
                                        #
    speeches$who <- gsub.e("Xavier A[xz]uara (?:Zúñiga|Núñez)" , "Xavier Azuara Zúñiga", speeches$who)
    speeches$who <- gsub.e("William Oswaldo Ochoa" , "Williams Oswaldo Ochoa", speeches$who)
    speeches$who <- gsub.e("Víctor Rafael Manríquez González" , "Víctor Rafael González Manríquez", speeches$who)
    speeches$who <- gsub.e("Víctor Oswaldo Sol[ií]s" , "Víctor Oswaldo Fuentes Solís", speeches$who)
    speeches$who <- gsub.e("Víctor Manuel Manriquez González" , "Víctor Manuel Manríquez González", speeches$who)
    speeches$who <- gsub.e("Víctor Jorrín Lozano" , "Víctor Humberto Jorrín Lozano", speeches$who)
    speeches$who <- gsub.e("Ulíses" , "Ulises", speeches$who)
    speeches$who <- gsub.e("Tomás Torres Marcado" , "Tomás Torres Mercado", speeches$who)
    speeches$who <-   gsub("Silvano [Bb]lan[cd]o de Deaquino" , "Silvano Blanco Deaquino", speeches$who)
    speeches$who <-   gsub("Silvano [Aa]ureoles [Cc]onejo" , "Silvano Aureoles Conejo", speeches$who)
    speeches$who <-   gsub("Sergio [Aa]ugusto Chan Lugo" , "Sergio Augusto Chan Lugo", speeches$who)
    speeches$who <- gsub.e("Núñez Monreal Magdalena del Socorro" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Secretaría Magdalena del Socorro Núñez" , "Magdalena del Socorro Núñez", speeches$who)
    speeches$who <- gsub.e("Sebastián(?: Alfonso)? de la Rosa Peláez" , "Sebastián Alfonso De la Rosa Peláez", speeches$who)
    speeches$who <- gsub.e("Ortíz" , "Ortiz", speeches$who)
    speeches$who <- gsub.e("Salgad$" , "Salgado", speeches$who)
    speeches$who <- gsub.e("Olguín" , "Olguín", speeches$who)
    speeches$who <- gsub.e("Chávez Conteras" , "Chávez Contreras", speeches$who)
    speeches$who <- gsub.e("Morneal" , "Monreal", speeches$who)
    speeches$who <-   gsub("Ricardo Anaya [Cc]ort[eé]s?" , "Ricardo Anaya Cortés", speeches$who)
    speeches$who <- gsub.e("Fijiwara" , "Fujiwara", speeches$who)
    speeches$who <- gsub.e("Saut Saut" , "Saut", speeches$who)
    speeches$who <- gsub.e("Raúl Paz Alonso" , "Raúl Paz Alonzo", speeches$who)
    speeches$who <- gsub.e("Raquel Jiménez Carrillo" , "Raquel Jiménez Cerrillo", speeches$who)
    speeches$who <- gsub.e("Patricia Guadalupe Peña Recío" , "Patricia Guadalupe Peña Recio", speeches$who)
    speeches$who <- gsub.e("Pacheco Rodríguez Ricardo Fidel" , "Ricardo Fidel Pacheco Rodríguez", speeches$who)
    speeches$who <- gsub.e("Merilyn Gómez Posos" , "Merilyn Gómez Pozos", speeches$who)
    speeches$who <- gsub.e("Martín Heredia Lizárraga" , "Martín Alonso Heredia Lizárraga", speeches$who)
    speeches$who <- gsub.e("Martín Alfonso Heredia Lizárraga" , "Martín Alonso Heredia Lizárraga", speeches$who)
    speeches$who <- gsub.e("Martha Beatriz Córdoba Bernal" , "Martha Beatriz Córdova Bernal", speeches$who)
    speeches$who <- gsub.e("Mario Guillén Guillén" , "Mario Francisco Guillén Guillén", speeches$who)
    speeches$who <- gsub.e("Maribel Henríquez Ramírez" , "Maribel Enríquez Ramírez", speeches$who)
    speeches$who <- gsub.e("María del Rocio" , "María del Rocio", speeches$who)
    speeches$who <- gsub.e("María del Carmen Guzmán Urbán" , "María del Carmen Guzmán Urban", speeches$who)
    speeches$who <- gsub.e("Mar[ií]a de las? Nieves Garc[íi]a$" , "María de las Nieves García Fernández", speeches$who)
    speeches$who <-   gsub("[Tt]orres Cofi[ñn]o" , "Torres Cofiño", speeches$who)
    speeches$who <- gsub.e("Marcelo de Jesús Torres$" , "Marcelo de Jesús Torres Cofino", speeches$who)
    speeches$who <- gsub.e("Fabio Beltrones Rivero" , "Fabio Beltrones Rivera", speeches$who)
    speeches$who <- gsub.e("Manlio Fabio Beltrones$" , "Manlio Fabio Beltrones Rivera", speeches$who)
    speeches$who <- gsub.e("Madalena del Socorro Núñez Monreal" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("González Roldan" , "González Roldán", speeches$who)
    speeches$who <- gsub.e("Luis Angel Espinosa Cházaro" , "Luis Angel Xariel Espinosa Cházaro", speeches$who)
    speeches$who <- gsub.e("Alcalde Lujan" , "Alcalde Luján", speeches$who)
    speeches$who <- gsub.e("Luis Alberto Villarreal$" , "Luis Alberto Villarreal García", speeches$who)
    speeches$who <- gsub.e("Loreni?a .veth Valles? Sampedro" , "Lorenia Yveth Valles Sampedro", speeches$who)
    speeches$who <- gsub.e("Leopoldo Sánchez Ruz" , "Leopoldo Sánchez Cruz", speeches$who)
    speeches$who <-   gsub("Julio C[ée]sar Moreno [Rr]ivera" , "Julio César Moreno Rivera", speeches$who)
    speeches$who <- gsub.e("Cesar Lorenzini" , "César Lorenzini", speeches$who)
    speeches$who <- gsub.e("Juan Fran?cisco Cá[cz][ae]res de la Fuente" , "Juan Francisco Cáceres de la Fuente", speeches$who)
    speeches$who <-   gsub("Juan [Bb]ueno Torio" , "Juan Bueno Torio", speeches$who)
    speeches$who <- gsub.e("J[.] Pilar Moreno Montoya" , "José Pilar Moreno Montoya", speeches$who)
    speeches$who <- gsub.e("José Luis Val$" , "José Luis Valle Magaña", speeches$who)
    speeches$who <- gsub.e("José Luis Muños Soria" , "José Luis Muñoz Soria", speeches$who)
    speeches$who <- gsub.e("José Luis Martínez Martínez" , "José Luis Márquez Martínez", speeches$who) # OJO: podría tbn ser Mtz Meléndez (suplente)
    speeches$who <- gsub.e("José Guillermo Amaya" , "José Guillermo Anaya", speeches$who)
    speeches$who <- gsub.e("(?:presidente )?José González Morf?[ií]n( Morf?[ií]n)?" , "José González Morfín", speeches$who)
    speeches$who <- gsub.e("presidente " , "", speeches$who)
    speeches$who <- gsub.e("Víctor Manuel Jorrín Serrano" , "Víctor Manuel Jorrín Lozano", speeches$who)
    speeches$who <- gsub.e("Víctor Humberto Jorrín Lozano" , "Víctor Manuel Jorrín Lozano", speeches$who)
    speeches$who <-   gsub("Silvano [Bb]lan[cd]o Deaquino" , "Silvano Blanco Deaquino", speeches$who)
    speeches$who <- gsub.e("Sergio Chan Lugo" , "Sergio Augusto Chan Lugo", speeches$who)
    speeches$who <- gsub.e("Ruben Acosta Montoya" , "Rubén Acosta Montoya", speeches$who)
    speeches$who <- gsub.e("Roy Angel Gómez Olguín" , "Roy Argel Gómez Olguín", speeches$who)
    speeches$who <-   gsub("Manuel rafael" , "Manuel Rafael", speeches$who)
    speeches$who <- gsub.e("Ladón de Guevara" , "Ladrón de Guevara", speeches$who)
    speeches$who <- gsub.e("^Manuel Huerta Ladrón" , "Manuel Rafael Huerta Ladrón", speeches$who) # there must be a better way
    speeches$who <-   gsub("Manuel Rafael [Hh]uert?a Ladrón de Guevara" , "Manuel Rafael Huerta Ladrón de Guevara", speeches$who)
    speeches$who <-   gsub("Rafael Manuel Huerta Ladrón de Guevara" , "Manuel Rafael Huerta Ladrón de Guevara", speeches$who)
    speeches$who <- gsub.e("Carpinteyro Caderón" , "Carpinteyro Calderón", speeches$who)
    speeches$who <-  sub.e("^.+El diputado Martín Alonso Heredia Lizárraga, la diputada Lizbeth Eugenia Rosas Montero, el diputado Luis Antonio González Roldán</b>: Sí, protesto.*$" , "varios-protestan-Mesa-Directiva", speeches$who)
    speeches$who <- gsub.e("Omar Borboa Becerra" , "Omar Antonio Borboa Becerra", speeches$who)
    speeches$who <- gsub.e("Mar[tí]h?a Beatriz Zavala Peniche" , "Beatriz Zavala Peniche", speeches$who)
    speeches$who <- gsub.e("Dunyasca" , "Dunyaska", speeches$who)
    speeches$who <- gsub.e("Mar[íi]a del Roc[íi]o" , "María del Rocío", speeches$who)
    speeches$who <- gsub.e("María de la Nieves García$" , "María de la Nieves García Fernández", speeches$who)
    speeches$who <- gsub.e("María Carmen Segura López" , "María Carmen López Segura", speeches$who)
    speeches$who <- gsub.e("Fonllen" , "Fonllem", speeches$who)
    speeches$who <- gsub.e("Marco Rosendo Medina Filigrana" , "Marcos Rosendo Medina Filigrana", speeches$who)
    speeches$who <-   gsub("Medina filigrana" , "Medina Filigrana", speeches$who)
    speeches$who <- gsub.e("^Rosendo(?: Marcos)? Medina Filigrana" , "Marcos Rosendo Medina Filigrana", speeches$who)
    speeches$who <- gsub.e("Cofño" , "Cofiño", speeches$who)
    speeches$who <- gsub.e("Cofino" , "Cofiño", speeches$who)
    speeches$who <- gsub.e("Magdalena del Socorro Núñez$" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Luis Alberto González Roldán" , "Luis Antonio González Roldán", speeches$who)
    speeches$who <- gsub.e("Loretra Ortiz Half" , "Loretta Ortiz Half", speeches$who)
    speeches$who <- gsub.e("Li[zs]beth Eugenia Rosas (?:Montero|Moreno)" , "Lizbeth Eugenia Rosas Montero", speeches$who)
    speeches$who <- gsub.e("Laura Jiménez Martel Cantú" , "Laura Ximena Martel Cantú", speeches$who)
    speeches$who <- gsub.e("Julissa Mejía Guardado" , "Julisa Mejía Guardado", speeches$who)
    speeches$who <- gsub.e("José Sergio Quiroga Manzur" , "José Sergio Manzur Quiroga", speeches$who)
    speeches$who <- gsub.e("José Everardo Gómez Nava" , "José Everardo Nava Gómez", speeches$who)
    speeches$who <- gsub.e("José Angelino Caamal Méndez" , "José Angelino Caamal Mena", speeches$who)
    speeches$who <- gsub.e("Benavidez Castañeda" , "Benavides Castañeda", speeches$who)
    speeches$who <- gsub.e("Jorge Iván Villalobos Seánez" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Jorge Iván Seáñez Villalobos" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Sotomayor Cháve$" , "Sotomayor Chávez", speeches$who)
    speeches$who <- gsub.e("Jesús Tolentito" , "Jesús Tolentino", speeches$who)
    speeches$who <- gsub.e("Homero Ricardo Niño de Rivera Val" , "Homero Ricardo Niño de Rivera Vela", speeches$who)
    speeches$who <- gsub.e("Heriberto Galindo Quiñones" , "Heriberto Manuel Galindo Quiñones", speeches$who)
    speeches$who <- gsub.e("Héctor Irineo Mares Cossío" , "Héctor Ireneo Mares Cossío", speeches$who)
    speeches$who <- gsub.e("Héctor Gutiérrez de la Garza" , "Héctor Humberto Gutiérrez de la Garza", speeches$who)
    speeches$who <- gsub.e("Graciela Saldaña Freire" , "Graciela Saldaña Fraire", speeches$who)
    speeches$who <- gsub.e("Gloria Saldaña Fraire" , "Graciela Saldaña Fraire", speeches$who)
    speeches$who <- gsub.e("Gerardo Villanueva Albarán" , "Gerardo Villanueva Albarrán", speeches$who)
    speeches$who <- gsub.e("Gavilán Rodolfo Dorador Pérez" , "Rodolfo Dorador Pérez Gavilán", speeches$who)
    speeches$who <- gsub.e("Francisco Antonio Mora Molina" , "Francisco Antonio Eduardo Mora Molina", speeches$who)
    speeches$who <- gsub.e("Francisco Antonio Durazo Montaño" , "Francisco Alfonso Durazo Montaño", speeches$who)
    speeches$who <- gsub.e("Francisco Alberto Cepeda González" , "Francisco Alberto Zepeda González", speeches$who)
    speeches$who <- gsub.e("^francisco" , "Francisco", speeches$who)
    speeches$who <- gsub.e("Fernando Zarate Salgado" , "Fernando Zárate Salgado", speeches$who)
    speeches$who <- gsub.e("de las Fuetes Hernández" , "de las Fuentes Hernández", speeches$who)
    speeches$who <- gsub.e("Fernando Charles Hernández" , "Fernando Charleston Hernández", speeches$who)
    speeches$who <- gsub.e("Muños Kapamas" , "Muñoz Kapamas", speeches$who)
    speeches$who <- gsub.e("Ernesto Germán Sánchez Gutiérrez" , "Ernesto Germán Sánchez Jiménez", speeches$who)
    speeches$who <- gsub.e("Erica del Carmen Velázquez Vacío" , "Erica del Carmen Velázquez Vacio", speeches$who)
    speeches$who <- gsub.e("Enrique Palomino Aubry de Castro" , "Enrique Aubry de Castro Palomino", speeches$who)
    speeches$who <- gsub.e("Eligio Cuitláhuac González Farías" , "Eligio Cuitláhuac González Farias", speeches$who)
    speeches$who <- gsub.e("El diputado Manuel" , "Manuel", speeches$who)
    speeches$who <- gsub.e("Dunia Eliane Preciado de la Vega" , "Dunia Eliane de la Vega Preciado", speeches$who)
    speeches$who <- gsub.e("Duna Eliane de la Vega Preciado" , "Dunia Eliane de la Vega Preciado", speeches$who)
    speeches$who <- gsub.e("David Pérez de Tejada Padilla" , "David Pérez Tejada Padilla", speeches$who)
    speeches$who <- gsub.e("Dario Zacarias Capuchino" , "Darío Zacarías Capuchino", speeches$who)
    speeches$who <- gsub.e("Danner González Roldán" , "Danner González Rodríguez", speeches$who)
    speeches$who <- gsub.e(" Damián Vidales Zepeda" , " Damián Zepeda Vidales", speeches$who)
    speeches$who <- gsub.e("Claudia Elena Aguila Torre$" , "Claudia Elena Aguila Torres", speeches$who)
    speeches$who <- gsub.e("Cinth.a Valladares Couoh" , "Cinthya Noemí Valladares Couoh", speeches$who)
    speeches$who <- gsub.e("Chantal Zepeda Escobar" , "Shantall Zepeda Escobar", speeches$who)
    speeches$who <- gsub.e("César Reynaldo Navarro de Alva" , "César Reynaldo Navarro de Alba", speeches$who)
    speeches$who <- gsub.e("Carlos Octavio Castellanos$" , "Carlos Octavio Castellanos Mijares", speeches$who)
    speeches$who <- gsub.e("Carlos Octavio Castellano Mijares" , "Carlos Octavio Castellanos Mijares", speeches$who)
    speeches$who <- gsub.e("Carlos Fernando Augusto Parra" , "Carlos Fernando Angulo Parra", speeches$who)
    speeches$who <- gsub.e("Borges Pasos Teresita de Jesús" , "Teresita de Jesús Borges Pasos", speeches$who)
    speeches$who <- gsub.e("Bonilla Jaime Juana" , "Juana Bonilla Jaime", speeches$who)
    speeches$who <- gsub.e("Bárbara Graciela Romo Fonseca" , "Bárbara Gabriela Romo Fonseca", speeches$who)
    speeches$who <- gsub.e("Aurora Aguilar Rodríguez" , "Aurora de la Luz Aguilar Rodríguez", speeches$who)
    speeches$who <- gsub.e("Arturo Escobar Vega" , "Arturo Escobar y Vega", speeches$who)
    speeches$who <- gsub.e("Arel[iy] Madrid [PT]ovilla" , "Areli Madrid Tovilla", speeches$who)
    speeches$who <- gsub.e("Antonio Astiazarán Gutiérrez" , "Antonio Francisco Astiazarán Gutiérrez", speeches$who)
    speeches$who <- gsub.e("Angulo Parra Carlos Fernando" , "Carlos Fernando Angulo Parra", speeches$who)
    speeches$who <- gsub.e("Angélica Rocío Melchor Vázquez" , "Angélica Rocío Melchor Vásquez", speeches$who)
    speeches$who <- gsub.e("Amalia García Medina" , "Amalia Dolores García Medina", speeches$who)
    speeches$who <- gsub.e("Alliet Bautista Bravo" , "Alliet Mariana Bautista Bravo", speeches$who)
    speeches$who <- gsub.e("Alfredo Maldonado Hernández" , "Alfredo Rivadeneyra Hernández", speeches$who)
    speeches$who <- gsub.e("Alfonso Inzunza Montaño" , "Alfonso Inzunza Montoya", speeches$who)
    speeches$who <- gsub.e("$Alfonso Durazo Montaño" , "Alfonso Francisco Durazo Montaño", speeches$who)
    speeches$who <- gsub.e("Alberto Escamilla Cerón" , "Alberto Leónides Escamilla Cerón", speeches$who)
    speeches$who <- gsub.e("Aceves y del Olmo Carlos Humberto" , "Carlos Humberto Aceves y del Olmo", speeches$who)
    speeches$who <- gsub.e("Loretta Ortiz Half" , "Loretta Ortiz Ahlf", speeches$who)
    speeches$who <- gsub.e("Claudia Elena Aguila Flores" , "Claudia Elena Aguila Torres", speeches$who)
    speeches$who <- gsub.e("Lizbeth Rosas Montero" , "Lizbeth Eugenia Rosas Montero", speeches$who)
    speeches$who <- gsub.e("Juan Marcos Issa Salomón" , "Salomón Juan Marcos Issa", speeches$who)
    speeches$who <- gsub.e("María de Carmen Martínez Santillán" , "María del Carmen Martínez Santillán", speeches$who)
    speeches$who <- gsub.e("María Fernando Romero Lozano" , "María Fernanda Romero Lozano", speeches$who)
    speeches$who <- gsub.e("Alfonso Francisco Durazo Montaño" , "Francisco Alfonso Durazo Montaño", speeches$who)
    speeches$who <- gsub.e("Francisco Zepeda González" , "Francisco Alberto Zepeda González", speeches$who)
    speeches$who <- gsub.e("Fernando Alfredo Rivadeneyra Hernández" , "Alfredo Rivadeneyra Hernández", speeches$who)
    speeches$who <- gsub.e("María Concepción Navarrete Vital" , "Ma. Concepción Navarrete Vital", speeches$who)
    speeches$who <- gsub.e("Cinthya Noem. Valladares Couoh" , "Cinthya Noemy Valladares Couoh", speeches$who)
    speeches$who <- gsub.e("María Guadalupe Mondragón González" , "Ma. Guadalupe Mondragón González", speeches$who)
    speeches$who <- gsub.e("Miguel Agustín Alonso Raya" , "Agustín Miguel Alonso Raya", speeches$who)
    speeches$who <- gsub.e("María Leticia Mendoza Curiel" , "Ma. Leticia Mendoza Curiel", speeches$who)
    speeches$who <- gsub.e("Víctor Hugo Roblero Gordillo" , "Héctor Hugo Roblero Gordillo", speeches$who)
    speeches$who <- gsub.e("Williams Oswaldo Ochoa Gallegos" , "Willy Ochoa Gallegos", speeches$who)
    speeches$who <- gsub.e("Frine Soraya Córdova Morán" , "Frine Soraya Córdoba Morán", speeches$who)
    speeches$who <- gsub.e("María del Socorro Núñez Monreal" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Palomino Enrique Aubry De Castro" , "Enrique Aubry De Castro Palomino", speeches$who)
    speeches$who <- gsub.e("María Teresa de Jesús Mojica Morga" , "Teresa de Jesús Mojica Morga", speeches$who)
    speeches$who <- gsub.e("Faustino Félix Chávez" , "Faustino Francisco Félix Chávez", speeches$who)
    speeches$who <- gsub.e("Lorenia Yveth Valles Sampedro" , "Lorenia Iveth Valles Sampedro", speeches$who)
    speeches$who <- gsub.e("Dora María Guadalupe Talamante Lemas" , "Dora María Guadalupe Talamanto Lemas", speeches$who)
    speeches$who <- gsub.e("" , "", speeches$who)
    sel2 <- grep.e("Barbosa Huerta", speeches$who) # Es un senador en sesión congreso general
    speeches$role[sel2] <- speeches$who[sel2] <- "senador"
    speeches$who <- gsub.e("Francisco Elena Corrales Corrales" , "Francisca Elena Corrales Corrales", speeches$who)
    speeches$who <- gsub.e("Elena Francisca Corrales Corrales" , "Francisca Elena Corrales Corrales", speeches$who)
    speeches$who <- gsub.e("César Augusto Chan Lugo" , "Sergio Augusto Chan Lugo", speeches$who)
    speeches$who <- gsub.e("Mar.a( de)? Mont?serrat Baeza Vallejo" , "María de Monserrat Baeza Vallejo", speeches$who)
    speeches$who <- gsub.e("Linda Marina Dolores Munive Temoltzin" , "Linda Marina Dolores Munive Tenoltzin", speeches$who)
    speeches$who <- gsub.e("Cristian Manuel Narváez Romero" , "Christian Manuel Narváez Romero", speeches$who)
    speeches$who <- gsub.e("Erwin Francisco Arriola Doroteo" , "Erwin Francisco Arreola Doroteo", speeches$who)
    speeches$who <- gsub.e("L[íi]lia[nm] Mara Flores Ortega( Rodr.guez)?" , "Líliam Mara Flores Ortega", speeches$who)
    speeches$who <- gsub.e("María Merced León Andablo" , "Ma. Merced León Andablo", speeches$who)
    speeches$who <- gsub.e("María Guadalupe Jaramillo Villa" , "Ma. Guadalupe Jaramillo Villa", speeches$who)
    speeches$who <- gsub.e("María Lucrecia Arzola God.nez" , "María Lucrecia Arzola Godines", speeches$who)
    speeches$who <- gsub.e("María Margarita García Rojas" , "Mariana Dunyaska García Rojas", speeches$who)
    speeches$who <- gsub.e("Lucía Rosales Villegas" , "Lucía Rosales Villega", speeches$who)
    speeches$who <- gsub.e("Carlos Alberto Aceves y Del Olmo" , "Carlos Humberto Aceves y Del Olmo", speeches$who)
    speeches$who <- gsub.e("Marilyn Gómez Pozos" , "Merilyn Gómez Pozos", speeches$who)
    speeches$who <- gsub.e("José Antonio González Roldán" , "Luis Antonio González Roldán", speeches$who)
    speeches$who <- gsub.e("Fernando Maldonado Hernández" , "Fernando Alfredo Maldonado Hernández", speeches$who)
    speeches$who <- gsub.e("Diana Carina Velázquez" , "Diana Karina Velázquez Ramírez", speeches$who)
    speeches$who <- gsub.e("Gerardo Hernández Tapia" , "Gerardo Xavier Hernández Tapia", speeches$who)
    speeches$who <- gsub.e("Jorge Villalobos Seáñez" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Consuelo Argüelles Loyola" , "Consuelo Argüelles Loya", speeches$who)
    speeches$who <- gsub.e("Carlos Guzmán Cervantes" , "Carlos Bernardo Guzmán Cervantes", speeches$who)
    speeches$who <- gsub.e("Miguel Alonso Heredia Lizárraga" , "Martín Alonso Heredia Lizárraga", speeches$who)
    speeches$who <- gsub.e("Robert López Suárez" , "Roberto López Suárez", speeches$who)
    speeches$who <- gsub.e("Víctor Díaz Palacios" , "Víctor Emanuel Díaz Palacios", speeches$who)
    speeches$who <- gsub.e("Carlos Garc.a Gonz.lez" , "Carlos Alberto García González", speeches$who)
    speeches$who <- gsub.e("^Ricardo Suárez$" , "Ricardo Astudillo Suárez", speeches$who)
    speeches$who <- gsub.e("Jorge De la Vega Membrillo" , "Jorge Federico De la Vega Membrillo", speeches$who)
    speeches$who <- gsub.e("José Francisco Cáceres De la Fuente" , "Juan Francisco Cáceres De la Fuente", speeches$who)
    speeches$who <- gsub.e("Elizabeth Yáñez Robles" , "Elizabeth Oswelia Yáñez Robles", speeches$who)
    speeches$who <- gsub.e("Mario Carrillo Huerta" , "Mario Miguel Carrillo Huerta", speeches$who)
    speeches$who <- gsub.e("Arturo Valle Magaña" , "José Luis Valle Magaña", speeches$who)
    speeches$who <- gsub.e("Francisco José Coronato Rodríguez" , "José Francisco Coronato Rodríguez", speeches$who)
    speeches$who <- gsub.e("José Antonio Sampayo Ortiz" , "Ramón Antonio Sampayo Ortiz", speeches$who)
    speeches$who <- gsub.e("María del Carmen López Segura" , "María Carmen López Segura", speeches$who)
    speeches$who <- gsub.e("Jorge Sergio Manzur Quiroga" , "José Sergio Manzur Quiroga", speeches$who)
    speeches$who <- gsub.e("Manuela Huerta Ladr.n de Guevara" , "Manuel Rafael Huerta Ladrón de Guevara", speeches$who)
    speeches$who <- gsub.e("Lis .ngel Espinosa Ch.zaro" , "Luis Angel Xariel Espinosa Cházaro", speeches$who)
    speeches$who <- gsub.e("Posadas Hernández Domitilo" , "Domitilo Posadas Hernández", speeches$who)
    speeches$who <- gsub.e("Mar[ií]a del? Roc.. Garc[íi]a Olmedo" , "María del Rocío Garcia Olmedo", speeches$who)
    speeches$who <- gsub.e("Damián Vidales Zepeda" , "Damián Zepeda Vidales", speeches$who)
    speeches$who <- gsub.e("Marcela Velázquez Sánchez" , "Maricela Velázquez Sánchez", speeches$who)
    speeches$who <- gsub.e("Eulalia Lourdes Quiñones Canales" , "Lourdes Eulalia Quiñones Canales", speeches$who)
    speeches$who <- gsub.e("Javier Azuara Zúñiga" , "Xavier Azuara Zúñiga", speeches$who)
    speeches$who <- gsub.e("Maya Guadalupe Mondragón González" , "Ma. Guadalupe Mondragón González", speeches$who)
    speeches$who <- gsub.e("Francisco Liceaga Arteaga Gerardo" , "Gerardo Francisco Liceaga Arteaga", speeches$who)
    speeches$who <- gsub.e("María Rosario Merlín García" , "María del Rosario Merlín García", speeches$who)
    speeches$who <- gsub.e("Merlín García María del Rosario" , "María del Rosario Merlín García", speeches$who)
    speeches$who <- gsub.e("María Luisa Alcalde Luján" , "Luisa María Alcalde Luján", speeches$who)
    speeches$who <- gsub.e("Víctor Manuel Díaz Palacios" , "Víctor Emanuel Díaz Palacios", speeches$who)
    speeches$who <- gsub.e("César Reynaldo Navarro De Alba" , "César Reynaldo Navarro De Alva", speeches$who)
    speeches$who <- gsub.e("Mar[ií]a de las Nieves Garc[íi]a Fern[áa]ndez" , "María de las Nieves García Fernández", speeches$who)
    speeches$who <- gsub.e("Claudia Bojórquez Javier" , "Claudia Elizabeth Bojórquez Javier", speeches$who)
    speeches$who <- gsub.e("Ang.lica Carreño Mijares" , "Angelina Carreño Mijares", speeches$who)
    speeches$who <- gsub.e("María Mónica García De la Fuente" , "Mónica García De la Fuente", speeches$who)
    speeches$who <- gsub.e("Nelly Lázara González Aguilar" , "Lázara Nelly González Aguilar", speeches$who)
    speeches$who <- gsub.e("Ramón Hernández Montalvo" , "Ramón Montalvo Hernández", speeches$who)
    speeches$who <- gsub.e("Francisco Arroyo Vieyra" , "Francisco Agustín Arroyo Vieyra", speeches$who)
    speeches$who <- gsub.e("Gabriel Eugenia Cortés Talamantes" , "Gabriela Eugenia Cortés Talamantes", speeches$who)
    speeches$who <- gsub.e("Gloria Rincón Chanona" , "Sonia Rincón Chanona", speeches$who)
    speeches$who <- gsub.e("Miguel Alfonso Vildosola Lacarra" , "Miguel Vildosola Lacarra", speeches$who)
    speeches$who <- gsub.e("María Dolores García Medina" , "Amalia Dolores García Medina", speeches$who)
    speeches$who <- gsub.e("Víctor Fuentes Sol[ií]s" , "Víctor Oswaldo Fuentes Solís", speeches$who)
    #speeches$who <- gsub.e("" , "", speeches$who)
    #
    # return manipulation to original data
    tmp.fix[sel.leg,] <- speeches
    speeches <- tmp.fix # restore name
    rm(tmp.fix,sel.leg,sel2)
}

# legislatura 60 fixes
sel.leg <- which(speeches$leg==60)
if (length(sel.leg) > 0){
    tmp.fix <- speeches # duplicate
    speeches <- speeches[sel.leg,] # subset from manipulation
    #
    speeches$who <- gsub.e("Gobernaci.n Juan Camilo Mouriño Terrazo; el Procurador General de la Rep.blica.+$" , "EXEC", speeches$who)
    speeches$who <- gsub.e("Relaciones Exteriores,? (?:licenciad[ao]|doctor) (?:(Luis )?Ernesto Derb.z(?: Bautista)?|Patricia Espinosa Cantellano).*$" , "EXEC", speeches$who)
    speeches$who <- gsub.e("Mar.a del Carmen Pinete Vargas y Lilia Guadalupe Merodio Reza" , "varios.protestan", speeches$who)
    speeches$who <- gsub.e("Hacienda y Cr.dito P.blico.? (?:doctor|licenciado) (?:Agust.n Carstens? Carstens|Francisco Gil Díaz)" , "EXEC", speeches$who)
    speeches$who <- gsub.e("Gobernaci.n.? licenciado Francisco Javier Ram.rez Acuña" , "EXEC", speeches$who)
    speeches$who <- gsub.e("Gobernaci.n, licenciado Carlos (?:Mar.a )?Abascal Carranza" , "EXEC", speeches$who)
    speeches$who <- gsub.e("Desarrollo Social, Mar.a Beatriz Zavala Peniche" , "EXEC", speeches$who)
    speeches$who <- gsub.e("SEGURIDAD PUBLICA,? GENARO GARCIA LUNA" , "EXEC", speeches$who)
    speeches$who <- gsub.e("SAGARPA,? ALBERTO CARDENAS JIMENEZ" , "EXEC", speeches$who)
    speeches$who <- gsub.e("HACIENDA Y CREDITO PUBLICO,? LICENCIADO FRANCISCO GIL DIAZ" , "EXEC", speeches$who)
    speeches$who <- gsub.e("GOBERNACION.? JUAN CAMILO MOURIÑO TERRAZO" , "EXEC", speeches$who)
    speeches$who <- gsub.e("DESARROLLO SOCIAL,? (?:MARIA|ANA) TERESA ARAND?A OROZCO" , "EXEC", speeches$who)
    #
    speeches$who <- gsub.e("YOLANDA GARMENDIA HERNANDEZ" , "YOLANDA MERCEDES GARMENDIA HERNANDEZ", speeches$who)
    speeches$who <- gsub.e("YARY GEBHARDT GARDUZA" , "YARY DEL CARMEN GEBHARDT GARDUZA", speeches$who)
    speeches$who <- gsub.e("YADIRA YVETTE TAMAYO HERRERA" , "YADHIRA YVETTE TAMAYO HERRERA", speeches$who)
    speeches$who <- gsub.e("YADIRA HERRERA TAMAYO" , "YADHIRA YVETTE TAMAYO HERRERA", speeches$who)
    speeches$who <- gsub.e("YADHIRA .VETTE TAMAYO HERRERA" , "YADHIRA YVETTE TAMAYO HERRERA", speeches$who)
    speeches$who <- gsub.e("WENCESLAO HERRARA COYAC" , "WENCESLAO HERRERA COYAC", speeches$who)
    speeches$who <- gsub.e("WENCESLAO HERRERA COÑAC" , "WENCESLAO HERRERA COYAC", speeches$who)
    speeches$who <- gsub.e("VOLANTINA" , "VALENTINA", speeches$who)
    speeches$who <- gsub.e("V[.] LUIS S.NCHEZ JIM.NEZ" , "VENANCIO LUIS SANCHEZ JIMENEZ", speeches$who)
    speeches$who <- gsub.e("VIOLETA (?:DEL (?:PILAR|PINAL) )?LAGUN.S VIVEROS?" , "VIOLETA DEL PILAR LAGUNES VIVEROS", speeches$who)
    speeches$who <- gsub.e("V.CTOR VALENCIA LEOPOLDO DE LOS SANTOS" , "VICTOR LEOPOLDO VALENCIA DE LOS SANTOS", speeches$who)
    speeches$who <- gsub.e("V.CTOR VALENCIA DE LOS SANTOS" , "VICTOR LEOPOLDO VALENCIA DE LOS SANTOS", speeches$who)
    speeches$who <- gsub.e("V.CTOR LEOPOLDO DE LOS SANTOS" , "VICTOR LEOPOLDO VALENCIA DE LOS SANTOS", speeches$who)
    speeches$who <- gsub.e("^V.CTOR TORRES$" , "VICTOR MANUEL TORRES HERRERA", speeches$who)
    speeches$who <- gsub.e("V.CTOR MANUEL MENDEZ LANZ YVETTE" , "VICTOR MANUEL MENDEZ LANZ", speeches$who)
    speeches$who <- gsub.e("V.CTOR MANUEL LIZARRAGA PEREZA" , "VICTOR MANUEL LIZARRAGA PERAZA", speeches$who)
    speeches$who <- gsub.e("VICTORIO MONTALVO ROJAS" , "VICTORIO RUBEN MONTALVO ROJAS", speeches$who)
    speeches$who <- gsub.e("V.CTOR AGUIRRE ALCALDE" , "VICTOR AGUIRRE ALCAIDE", speeches$who)
    speeches$who <- gsub.e("VERASTEGUI OSTOS CESAR AUGUSTO" , "CESAR AUGUSTO VERASTEGUI OSTOS", speeches$who)
    speeches$who <- gsub.e("VAZQUEZ MARTINEZ ALBERTO" , "ALBERTO VAZQUEZ MARTINEZ", speeches$who)
    speeches$who <- gsub.e("VALENTINA (?:VANIA )?BATRES GUADARRAMA" , "VALENTINA VALIA BATRES GUADARRAMA", speeches$who)
    speeches$who <- gsub.e("VALENTINA GUADARRAMA" , "VALENTINA VALIA BATRES GUADARRAMA", speeches$who)
    speeches$who <- gsub.e("TONATIHU" , "TONATIUH", speeches$who)
    speeches$who <- gsub.e("TONATIUH IT?ZCOATL BRAVO PADILLA" , "ITZCOATL TONATIUH BRAVO PADILLA", speeches$who)
    speeches$who <- gsub.e("THOMAS DEL TORO DEL VILLAR" , "TOMAS DEL TORO DEL VILLAR", speeches$who)
    speeches$who <- gsub.e("TERESA DE JESUS ALCOCER Y GA..A" , "TERESA DE JESUS ALCOCER Y GAZCA", speeches$who)
    speeches$who <- gsub.e("SUSANA SARRIA CARRASCO CARDENAS" , "SUSANA SARAHI CARRASCO CARDENAS", speeches$who)
    speeches$who <- gsub.e("SUSANA SARAHI CARRASCO ALTAMIRANO" , "SUSANA SARAHI CARRASCO CARDENAS", speeches$who)
    speeches$who <- gsub.e("SONIA NOELIA IBARRA FRANQUEZ" , "SONIA NOHELIA IBARRA FRANQUEZ", speeches$who)
    speeches$who <- gsub.e("SONIA IBARRA FRANQUES" , "SONIA NOHELIA IBARRA FRANQUEZ", speeches$who)
    speeches$who <- gsub.e("SILVINA LUNA RODRIGUEZ" , "SILVIA LUNA RODRIGUEZ", speeches$who)
    speeches$who <- gsub.e("SILVIA DE GANTE" , "SILVIA EMILIA DEGANTE ROMERO", speeches$who)
    speeches$who <- gsub.e("SERGIO EDUARDO DE LA TORRE JARAMILLO" , "EDUARDO SERGIO DE LA TORRE JARAMILLO", speeches$who)
    speeches$who <- gsub.e("SERGIO DE LA TORRE JARAMILLO" , "EDUARDO SERGIO DE LA TORRE JARAMILLO", speeches$who)
    speeches$who <- gsub.e("^SARA CASTELLANOS$" , "SARA ISABEL CASTELLANOS CORTES", speeches$who)
    speeches$who <- gsub.e("SAMUEL PALMA" , "VICTOR SAMUEL PALMA CESAR", speeches$who)
    speeches$who <- gsub.e("SAMUEL DIEGO AGUILAR SOLIS" , "SAMUEL AGUILAR SOLIS", speeches$who)
    speeches$who <- gsub.e("^SAMUEL AGUILAR$" , "SAMUEL AGUILAR SOLIS", speeches$who)
    speeches$who <- gsub.e("SALVADOR DEL TORO BARAJAS" , "SALVADOR BARAJAS DEL TORO", speeches$who)
    speeches$who <- gsub.e("RUTILIO CRUZ ESCANDON CARDENAS" , "RUTILIO CRUZ ESCANDON CADENAS", speeches$who)
    speeches$who <- gsub.e("^RUTILIO CRUZ ESCANDON$" , "RUTILIO CRUZ ESCANDON CADENAS", speeches$who)
    speeches$who <- gsub.e("^RUTILIO ESCANDON$" , "RUTILIO CRUZ ESCANDON CADENAS", speeches$who)
    speeches$who <- gsub.e("^RUTILIO ESCANDON CADENAS$" , "RUTILIO CRUZ ESCANDON CADENAS", speeches$who)
    speeches$who <- gsub.e("RUTH ZAVALE?T?A SAL.ADO" , "RUTH ZAVALETA SALGADO", speeches$who)
    speeches$who <- gsub.e("^RUTH ZAVALETA$" , "RUTH ZAVALETA SALGADO", speeches$who)
    speeches$who <- gsub.e("ROSAURA (?:VIRGINIA )?DENEGRE[- ]VAUGHT RAMIREZ" , "ROSAURA VIRGINIA DENEGRE VAUGHT RAMIREZ", speeches$who)
    speeches$who <- gsub.e("ROSARIO ORTIZ MAGALLON" , "ROSARIO IGNACIA ORTIZ MAGALLON", speeches$who)
    speeches$who <- gsub.e("ROSAEL RAMOS" , "JOSE NICOLAS MORALES RAMOS", speeches$who)
    speeches$who <- gsub.e("ROSA ELIA RODRIGUEZ GUZMAN" , "ROSA ELIA ROMERO GUZMAN", speeches$who)
    speeches$who <- gsub.e("ROSA ELBA SORIANO SANCHEZ" , "ROSA ELVA SORIANO SANCHEZ", speeches$who)
    speeches$who <- gsub.e("ROMERO GUZMAN ROSA ELIA" , "ROSA ELIA ROMERO GUZMAN", speeches$who)
    speeches$who <- gsub.e("^ROMO JIMENEZ$" , "MARTHA ANGELICA ROMO JIMENEZ", speeches$who)
    speeches$who <- gsub.e("ROGELIO CAR.AJAL TEJ.DA" , "ROGELIO CARBAJAL TEJADA", speeches$who)
    speeches$who <- gsub.e("RODRIGUEZ FRANCISCO JAVIER PAREDES RODRIGUEZ" , "FRANCISCO JAVIER PAREDES RODRIGUEZ", speeches$who)
    speeches$who <- gsub.e("^RODOLFO ENRIQUEZ$" , "LUIS RODOLFO ENRIQUEZ MARTINEZ", speeches$who)
    speeches$who <- gsub.e("ROCIO MARIA DEL CARMEN MORGAN FRANCO" , "ROCIO DEL CARMEN MORGAN FRANCO", speeches$who)
    speeches$who <- gsub.e("ROCIO DEL CARMEN MORGAN FRANCO" , "ROCIO DEL CARMEN MORGAN FRANCO", speeches$who)
    speeches$who <- gsub.e("ROCIO MORGAN FRANCO" , "ROCIO DEL CARMEN MORGAN FRANCO", speeches$who)
    speeches$who <- gsub.e("^ROBINSON USCANGA$" , "ROBINSON USCANGA CRUZ", speeches$who)
    speeches$who <- gsub.e("ROBERTO CEREZO TORRES" , "ROBERTO EFREN CEREZO TORRES", speeches$who)
    speeches$who <- gsub.e("RIVERO RIVERO ROLANDO" , "ROLANDO RIVERO RIVERO", speeches$who)
    speeches$who <- gsub.e("RICARDO FRANCO CAZAREZ" , "RICARDO FRANCO CAZARES", speeches$who)
    speeches$who <- gsub.e("^RICARDO CANAVATI$" , "JESUS RICARDO CANAVATI TAFICH", speeches$who)
    speeches$who <- gsub.e("RENE LEZAMA ARDILLAS" , "RENE LEZAMA ARADILLAS", speeches$who)
    speeches$who <- gsub.e("RAUL PADILLA OROZCO" , "RAUL ALEJANDRO PADILLA OROZCO", speeches$who)
    speeches$who <- gsub.e("RAMON P.CHECO YAÑEZ" , "RAMON FELIX PACHECO LLANES", speeches$who)
    speeches$who <- gsub.e("RAMON LANDEROS GONZALE." , "RAMON LANDEROS GONZALEZ", speeches$who)
    speeches$who <- gsub.e("RAMON BORJA ALMONTE" , "RAMON ALMONTE BORJA", speeches$who)
    speeches$who <- gsub.e("RAFAEL ELIAS SANCHEZ JIMEMEZ", "RAFAEL ELIAS SANCHEZ CABRALES", speeches$who)
    speeches$who <- gsub.e("RAFAEL RAMOS BECERRIL", "RAFAEL PLACIDO RAMOS BECERRIL", speeches$who)
    speeches$who <- gsub.e("RAFAEL ELIAS SANCHEZ JIMENEZ", "RAFAEL ELIAS SANCHEZ CABRALES", speeches$who)
    speeches$who <- gsub.e("^OJEDA CAMACHO$", "GILBERTO OJEDA CAMACHO", speeches$who)
    speeches$who <- gsub.e("^OCTAVIO RAMIREZ VARGAS$", "OCTAVIO MARTINEZ VARGAS", speeches$who)
    speeches$who <- gsub.e("RACIEL CRUZ PEREZ", "RACIEL PEREZ CRUZ", speeches$who)
    speeches$who <- gsub.e("PEDRO LANDEROS LOPEZ", "PEDRO LANDERO LOPEZ", speeches$who)
    speeches$who <- gsub.e("^PEDRO CORTES$", "SANTIAGO GUSTAVO PEDRO CORTES", speeches$who)
    speeches$who <- gsub.e("PATRICIA VILLANUEVA ABRA.AN", "PATRICIA VILLANUEVA ABRAJAN", speeches$who)
    speeches$who <- gsub.e("PATRICIA VILLANUEVA ALBARRAN", "PATRICIA VILLANUEVA ABRAJAN", speeches$who)
    speeches$who <- gsub.e("PATRICIA OBDULIA CASTILLO ROMERO" , "PATRICIA OBDULIA DE JESUS CASTILLO ROMERO", speeches$who)
    speeches$who <- gsub.e("PATRICIA OBDULIA DE JESUS CASTRO ROMERO" , "PATRICIA OBDULIA DE JESUS CASTILLO ROMERO", speeches$who)
    speeches$who <- gsub.e("PASCUAL BELLIZIA ROSIQUE" , "PASCUAL BELLIZZIA ROSIQUE", speeches$who)
    speeches$who <- gsub.e("^PABLO LEOPOLDO ARREOLA$" , "PABLO LEOPOLDO ARREOLA ORTEGA", speeches$who)
    speeches$who <- gsub.e("PABLO ARREOLA ORTEGA" , "PABLO LEOPOLDO ARREOLA ORTEGA", speeches$who)
    speeches$who <- gsub.e("OSCAR MANUEL MOHAMAR DAINITIN" , "OSCAR MIGUEL MOHAMAR DAINITIN", speeches$who)
    speeches$who <- gsub.e("OSCAR GUSTAVO CARDENAS MONRROY" , "OSCAR GUSTAVO CARDENAS MONROY", speeches$who)
    speeches$who <- gsub.e("ORALIA MARIA ORALIA VEGA ORTIZ" , "MARIA ORALIA VEGA ORTIZ", speeches$who)
    speeches$who <- gsub.e("ORALIA VEGA ORTIZ" , "MARIA ORALIA VEGA ORTIZ", speeches$who)
    speeches$who <- gsub.e("OCHOA LOPEZ NABOR" , "NABOR OCHOA LOPEZ", speeches$who)
    speeches$who <- gsub.e("NEPTALI GARZON CONTRERAS", "NEFTALI GARZON CONTRERAS", speeches$who)
    speeches$who <- gsub.e("NARCI.O ALBERTO AMADOR LEAL" , "NARCISO ALBERTO AMADOR LEAL", speeches$who)
    speeches$who <- gsub.e("NARCI.O AMADOR LEAL" , "NARCISO ALBERTO AMADOR LEAL", speeches$who)
    speeches$who <- gsub.e("NELLY HURTADO PEREZ" , "NELLY ASUNCION HURTADO PEREZ", speeches$who)
    speeches$who <- gsub.e("MONREAL SUSANA AVILA" , "SUSANA MONREAL AVILA", speeches$who)
    speeches$who <- gsub.e("MOISES DAGDUG LUTZOW" , "MOISES FELIX DAGDUG LUTZOW", speeches$who)
    speeches$who <- gsub.e("^NABOR OCHOA$", "NABOR OCHOA LOPEZ", speeches$who)
    speeches$who <- gsub.e("MONICA TZA..A ARRIOLA GORDILLO", "MONICA TZASNA ARRIOLA GORDILLO", speeches$who)
    speeches$who <- gsub.e("^MONICA TZASNA ARRIOLA$", "MONICA TZASNA ARRIOLA GORDILLO", speeches$who)
    speeches$who <- gsub.e("^MONICA ARRIOLA$", "MONICA TZASNA ARRIOLA GORDILLO", speeches$who)
    speeches$who <- gsub.e("MONICA ARR.OLA GORDILLO", "MONICA TZASNA ARRIOLA GORDILLO", speeches$who)
    speeches$who <- gsub.e("^MONICA FERNANDEZ$", "MONICA FERNANDEZ BALBOA", speeches$who)
    speeches$who <- gsub.e("^MOHAMAR DAINITIN$", "OSCAR MIGUEL MOHAMAR DAINITIN", speeches$who)
    speeches$who <- gsub.e("MIRNA RINCON VARGAS", "MIRNA CECILIA RINCON VARGAS", speeches$who)
    speeches$who <- gsub.e("MIRIAM GABRIELA CARDENAS DE LAS TORRES", "MIRIAM GABRIELA CARDENAS DE LA TORRE", speeches$who)
    speeches$who <- gsub.e("MIGUEN ANGEL", "MIGUEL ANGEL", speeches$who)
    speeches$who <- gsub.e("MIGUEL ANGEL JIMENEZ .ODINE.", "MIGUEL ANGEL JIMENEZ GODINEZ", speeches$who)
    speeches$who <- gsub.e("MARTIN E?STEFANONNI MAZZOCO", "MARTIN STEFANONNI MAZZOCCO", speeches$who)
    speeches$who <- gsub.e("MARTHA HILDA GONZALES CALDERON", "MARTHA HILDA GONZALEZ CALDERON", speeches$who)
    speeches$who <- gsub.e("MARTHA GARCIA MULLER", "MARTHA MARGARITA GARCIA MULLER", speeches$who)
    speeches$who <- gsub.e("MARTHA DIAZ GORDILLO", "MARTHA CECILIA DIAZ GORDILLO", speeches$who)
    speeches$who <- gsub.e("MARTHA TAGLE MARTINEZ", "MARTHA ANGELICA TAGLE MARTINEZ", speeches$who)
    speeches$who <- gsub.e("MARISOL MORA CUERVAS", "MARISOL MORA CUEVAS", speeches$who)
    speeches$who <- gsub.e("MARICELA CONTERAS JULIAN", "MARICELA CONTRERAS JULIAN", speeches$who)
    speeches$who <- gsub.e("MARIA SOLEDAD DIMAS FRESCAS", "MARIA SOLEDAD LIMAS FRESCAS", speeches$who)
    speeches$who <- gsub.e("MARIA SOFIA CASTRO ROMERO", "MARIA SOFIA DEL PERPETUO SOCORRO CASTRO ROMERO", speeches$who)
    speeches$who <- gsub.e("MARIA OLGA PATRICIA CHOZAS Y CHOZAS", "OLGA PATRICIA CHOZAS Y CHOZAS", speeches$who)
    speeches$who <- gsub.e("MARIANO GONZALEZ ARURA", "MARIANO GONZALEZ ZARUR", speeches$who)
    speeches$who <- gsub.e("^MARIA NIEVES NORIEGA BLANCO$", "MARIA ELENA DE LAS NIEVES NORIEGA BLANCO VIGIL", speeches$who)
    speeches$who <- gsub.e("MARIA MERCEDE.? MACIEL OR?TIZ", "MARIA MERCEDES MACIEL ORTIZ", speeches$who)
    speeches$who <- gsub.e("MARIA MANUELL-GOMEZ ANGULO", "MARIA MANUELL GOMEZ ANGULO", speeches$who)
    speeches$who <- gsub.e("MARIA GUADALUPE GARCIA NORIEGA", "MARIA GUADALUPE JOSEFINA GARCIA NORIEGA", speeches$who)
    speeches$who <- gsub.e("MARIA DE GUADALUPE JOSEFINA GARCIA NORIEGA", "MARIA GUADALUPE JOSEFINA GARCIA NORIEGA", speeches$who)
    speeches$who <- gsub.e("MARIA EUGENIA JIMENEZ. VALENZUELA", "MARIA EUGENIA JIMENEZ VALENZUELA", speeches$who)
    speeches$who <- gsub.e("MARIA ELENA ALVAREZ BERNAL DE VIVENVIO", "MARIA ELENA ALVAREZ BERNAL", speeches$who)
    speeches$who <- gsub.e("MARIA DE LOS ANGELES JIMENEZ CASTILLO", "MARIA DE LOS ANGELES JIMENEZ DEL CASTILLO", speeches$who)
    speeches$who <- gsub.e("MARIA DEL? CARMEN? SALVATORIO? BRONCA", "MARIA DEL CARMEN SALVATORI BRONCA", speeches$who)
    speeches$who <- gsub.e("MARIA DEL CARMEN CARBAJAL ADAME", "MARIA DEL CARMEN CARVAJAL ADAME", speeches$who)
    speeches$who <- gsub.e("MARCO SALAS CONTRERAS", "MARCOS SALAS CONTRERAS", speeches$who)
    speeches$who <- gsub.e("MARCO HERIBERTO OROZCO RUIZ VELAZCO", "MARCO HERIBERTO OROZCO RUIZ VELASCO", speeches$who)
    speeches$who <- gsub.e("MARCO HERIBERTO RUIZ VELASCO", "MARCO HERIBERTO OROZCO RUIZ VELASCO", speeches$who)
    speeches$who <- gsub.e("MANUEL PORTILL. DIE?GUEZ", "MANUEL PORTILLA DIEGUEZ", speeches$who)    
    speeches$who <- gsub.e("LUIS FERNANDO RODRIGUEZ AHUNADA", "LUIS FERNANDO RODRIGUEZ AHUMADA", speeches$who)
    speeches$who <- gsub.e("^LUIS FERNANDO RODRIGUEZ$", "LUIS FERNANDO RODRIGUEZ AHUMADA", speeches$who)
    speeches$who <- gsub.e("LUIS ENRIQUE BENITEZ ARTEAGA", "LUIS ENRIQUE BENITEZ OJEDA", speeches$who)
    speeches$who <- gsub.e("LUIS ALBERTO RODRIGUEZ", "LUIS ALBERTO RODRIGUEZ VARILLAS", speeches$who)
    speeches$who <- gsub.e("LUIS ALEJANDRO RODRIGUEZ", "LUIS ALBERTO RODRIGUEZ VARILLAS", speeches$who)
    speeches$who <- gsub.e("LUCIANA SUSANA MENDOZA MORALES", "LUCIA SUSANA MENDOZA MORALES", speeches$who)
    speeches$who <- gsub.e("^LORENA MARTINEZ$", "LORENA MARTINEZ RODRIGUEZ", speeches$who)
    speeches$who <- gsub.e("LILIANA CARVAJAL MENDEZ", "LILIANA CARBAJAL MENDEZ", speeches$who)
    speeches$who <- gsub.e("LILIA (?:GUADALUPE )?MERI?ODIO (?:R.ZA|RIVAS)", "LILIA GUADALUPE MERODIO REZA", speeches$who)
    speeches$who <- gsub.e("^LETICIA HERRERA$", "JUANA LETICIA HERRERA ALE", speeches$who)
    speeches$who <- gsub.e("LETICIA DIAZ DE LEON(?: TORRES?)?", "LETICIA DIAZ DE LEON TORRES", speeches$who)
    speeches$who <- gsub.e("LEONARDO CURIEL PRECIADO", "LEOBARDO CURIEL PRECIADO", speeches$who)
    speeches$who <- gsub.e("LAY.A SANSORES SAN ROMAN", "LAYDA ELENA SANSORES SAN ROMAN", speeches$who)
    speeches$who <- gsub.e("^LAYDA SANSORES$", "LAYDA ELENA SANSORES SAN ROMAN", speeches$who)
    speeches$who <- gsub.e("LARISA MONTIEL LUIS", "LARIZA MONTIEL LUIS", speeches$who)
    speeches$who <- gsub.e("JUAN VICTORIA ALBA", "JUAN VICTORIA ALVA", speeches$who)
    speeches$who <- gsub.e("JUAN NICASIO OCHOA GUERRA", "JUAN NICASIO GUERRA OCHOA", speeches$who)
    speeches$who <- gsub.e("JUAN NICASIO GUERRAS? OCHOA", "JUAN NICASIO GUERRA OCHOA", speeches$who)
    speeches$who <- gsub.e("^JUAN NICASIO GUERRA$", "JUAN NICASIO GUERRA OCHOA", speeches$who)
    speeches$who <- gsub.e("JUAN MANUEL SANDOVAL MURGUIA", "JUAN MANUEL SANDOVAL MUNGUIA", speeches$who)
    speeches$who <- gsub.e("^JUAN JOSE RODRIGUEZ$", "JUAN JOSE RODRIGUEZ PRATS", speeches$who)
    speeches$who <- gsub.e("^JUAN GUERRA OCHOA$", "JUAN NICASIO GUERRA OCHOA", speeches$who)
    speeches$who <- gsub.e("^JUAN GUERRA$", "JUAN NICASIO GUERRA OCHOA", speeches$who)
    speeches$who <- gsub.e("JUAN FRANCISCO RIVERA BEDOLLA", "JUAN FRANCISCO RIVERA BEDOYA", speeches$who)
    speeches$who <- gsub.e("^JUAN CARLOS VELASCO$", "JUAN CARLOS VELASCO PEREZ", speeches$who)
    speeches$who <- gsub.e("^JUANA LETICIA HERRERA A$", "JUANA LETICIA HERRERA ALE", speeches$who)
    speeches$who <- gsub.e("^JUAN ADOLFO ORCI$", "JUAN ADOLFO ORCI MARTINEZ", speeches$who)
    speeches$who <- gsub.e("JOSE RUBEN ESCAGEDA JIMENEZ", "JOSE RUBEN ESCAJEDA JIMENEZ", speeches$who)
    speeches$who <- gsub.e("JOSE ROSAS ESPURIO TORRES", "JOSE ROSAS AISPURO TORRES", speeches$who)
    speeches$who <- gsub.e("^JOSE ROSAS AISPURO$", "JOSE ROSAS AISPURO TORRES", speeches$who)
    speeches$who <- gsub.e("^JOSE MURAT$", "JOSE MURAT CASAB", speeches$who)
    speeches$who <- gsub.e("JOSE L..S ESPINOSA P..A", "JOSE LUIS ESPINOSA PIÑA", speeches$who)
    speeches$who <- gsub.e("JOSE LUIS CONTRERAS COETO", "JOSE LUIS CONTRERAS CUETO", speeches$who)
    speeches$who <- gsub.e("JOSE LUIS BLANCO PAVON", "JOSE LUIS BLANCO PAJON", speeches$who)
    speeches$who <- gsub.e("JOSE LUIS AGUILAR RICO", "JOSE LUIS AGUILERA RICO", speeches$who)
    speeches$who <- gsub.e("JOSE (?:JACQUES|JACKS) MEDINA", "JOSE JACQUES Y MEDINA", speeches$who)
    speeches$who <- gsub.e("^JOSE IGNACIO RUBIO CHAVEZ$", "JOSE IGNACIO ALBERTO RUBIO CHAVEZ", speeches$who)
    speeches$who <- gsub.e("JOSE GUILLERMO VELASQUEZ GUTIERREZ", "JOSE GUILLERMO VELAZQUEZ GUTIERREZ", speeches$who)
    speeches$who <- gsub.e("^JOSE GUADALUPE RIVERA$", "JOSE GUADALUPE RIVERA RIVERA", speeches$who)
    speeches$who <- gsub.e("JOSE GILDARDO (?:GUERRERO )?TORRES?", "JOSE GILDARDO GUERRERO TORRES", speeches$who)
    speeches$who <- gsub.e("^JOSE ASCENSION ORIHUELA$", "JOSE ASCENSION ORIHUELA BARCENAS", speeches$who)
    speeches$who <- gsub.e("JOSE ASCEN.ION? ORIHUELA BARCENAS", "JOSE ASCENSION ORIHUELA BARCENAS", speeches$who)
    speeches$who <- gsub.e("JOSE ARMANDO ORIHUELA TREJO", "JOSE AMADO ORIHUELA TREJO", speeches$who)
    speeches$who <- gsub.e("JOSE ALONSO SUAREZ DEL REAL Y AGUILERA", "JOSE ALFONSO SUAREZ DEL REAL Y AGUILERA", speeches$who)
    speeches$who <- gsub.e("JOSE ALONSO SUAREZ DEL REAL$", "JOSE ALFONSO SUAREZ DEL REAL Y AGUILERA", speeches$who)
    speeches$who <- gsub.e("JOSE ALONSO SUAREZ DEL REAL Y$", "JOSE ALFONSO SUAREZ DEL REAL Y AGUILERA", speeches$who)
    speeches$who <- gsub.e("ZERNMEÑO", "ZERMEÑO", speeches$who)
    speeches$who <- gsub.e("JORGE Z.RME.O INFANTE", "JORGE ZERMEÑO INFANTE", speeches$who)
    speeches$who <- gsub.e("JORGE ZERMEÑO (?:INFAMANTE|IBARRA|ORTIZ)", "JORGE ZERMEÑO INFANTE", speeches$who)
    speeches$who <- gsub.e("^JORGE ZERME.O$", "JORGE ZERMEÑO INFANTE", speeches$who)
    speeches$who <- gsub.e("^JORGE EMILIO GONZALEZ$", "JORGE EMILIO GONZALEZ MARTINEZ", speeches$who)
    speeches$who <- gsub.e("JORGE RUBEN GONZALEZ NORDHAUSEN", "JORGE RUBEN NORDHAUSEN GONZALEZ", speeches$who)
    speeches$who <- gsub.e("JORGE MARIO LESCIUER TALAVERA", "JORGE MARIO LESCIEUR TALAVERA", speeches$who)
    speeches$who <- gsub.e("JORGE JIMENEZ ZERMEÑO INFANTE", "JORGE ZERMEÑO INFANTE", speeches$who)
    speeches$who <- gsub.e("JOAQUIN H. VELA GONZALEZ", "JOAQUIN HUMBERTO VELA GONZALEZ", speeches$who)
    speeches$who <- gsub.e("JOAQUIN DE LOS SANTOS MOLINA", "JOAQUIN CONRADO DE LOS SANTOS MOLINA", speeches$who)
    speeches$who <- gsub.e("^JESUS DIAZ ATHIE$", "ANTONIO DE JESUS DIAZ ATHIE", speeches$who)
    speeches$who <- gsub.e("JESUS CUAUHTEMOC JESUS VELASCO OLIVA", "JESUS CUAUHTEMOC VELASCO OLIVA", speeches$who)
    speeches$who <- gsub.e("JOAQUIN DIA. MENA", "JOAQUIN JESUS DIAZ MENA", speeches$who)
    speeches$who <- gsub.e("JESUS RAMIREZ STRABOS", "JESUS RAMIREZ STABROS", speeches$who)
    speeches$who <- gsub.e("JESUS HUMBERTO ZAZUELA AGUILAR", "JESUS HUMBERTO ZAZUETA AGUILAR", speeches$who)
    speeches$who <- gsub.e("JESUS ARREN?DONDO V.LA.QUEZ", "JESUS ARREDONDO VELAZQUEZ", speeches$who)
    speeches$who <- gsub.e("JAVIER ZAMBRANO ELIZONDO", "JAVIER MARTIN ZAMBRANO ELIZONDO", speeches$who)
    speeches$who <- gsub.e("JACINTO GOMEZ PADILLAS", "JACINTO GOMEZ PASILLAS", speeches$who)
    speeches$who <- gsub.e("GONZALES", "GONZALEZ", speeches$who)
    speeches$who <- gsub.e("JAVIER ESTRADA GONZALEZ", "FAUSTINO JAVIER ESTRADA GONZALEZ", speeches$who)
    speeches$who <- gsub.e("JAVIER FAUSTINO ESTRADA GONZALEZ", "FAUSTINO JAVIER ESTRADA GONZALEZ", speeches$who)
    speeches$who <- gsub.e("JACINTO GONZALEZ PASILLAS", "JACINTO GOMEZ PASILLAS", speeches$who)
    speeches$who <- gsub.e("^JACINTO GOMEZ PA.ILLA$", "JACINTO GOMEZ PASILLAS", speeches$who)
    speeches$who <- gsub.e("^IVETTE RAMIREZ CORRAL$", "IVETTE JACQUELINE RAMIREZ CORRAL", speeches$who)
    speeches$who <- gsub.e("IT?ZCOAT?L TONATIUH? BRAVO PADILLA", "ITZCOATL TONATIUH BRAVO PADILLA", speeches$who)
    speeches$who <- gsub.e("ISMAEL PERAZA VALDES", "ISMAEL PERAZA VALDEZ", speeches$who)
    speeches$who <- gsub.e("ISIDRO PEDROZA CHAVEZ", "ISIDRO PEDRAZA CHAVEZ", speeches$who)
    speeches$who <- gsub.e("^ISIDRO PEDRAZA$", "ISIDRO PEDRAZA CHAVEZ", speeches$who)
    speeches$who <- gsub.e("IRMA PIÑEIRO ARIAS", "IRMA PIÑEYRO ARIAS", speeches$who)
    speeches$who <- gsub.e("^IRINEO MENDOZA$", "IRINEO MENDOZA MENDOZA", speeches$who)
    speeches$who <- gsub.e("IÑIGO (?:ANTONIO )?LAVIADA HERNANDEZ", "IÑIGO ANTONIO FRANCISCO LAVIADA HERNANDEZ", speeches$who)
    speeches$who <- gsub.e("^HUMBERTO ZAZUETA$", "HUMBERTO ZAZUETA AGUILAR", speeches$who)
    speeches$who <- gsub.e("HUMBERTO WIL?FR.DO ALONSO RAZO", "HUMBERTO WILFRIDO ALONSO RAZO", speeches$who)
    speeches$who <- gsub.e("HUMBERTO LOPEZ LENA CRUZ", "CRUZ HUMBERTO LOPEZ LENA", speeches$who)
    speeches$who <- gsub.e("^HUMBERTO LOPEZ LENA$", "CRUZ HUMBERTO LOPEZ LENA", speeches$who)
    speeches$who <- gsub.e("^HUMBERTO DAVILA EZQUIVEL$", "HUMBERTO DAVILA ESQUIVEL", speeches$who)
    speeches$who <- gsub.e("HORACIO GARZA GARZA", "HORACIO EMIGDIO GARZA GARZA", speeches$who)
    speeches$who <- gsub.e("HECTOR MARCIAL ALVAREZ", "HECTOR NARCIA ALVAREZ", speeches$who)
    speeches$who <- gsub.e("HECTOR LARIOS CORDOBA", "HECTOR LARIOS CORDOVA", speeches$who)
    speeches$who <- gsub.e("^GUSTAVO SANTIAGO PEDRO CORTES$", "SANTIAGO GUSTAVO PEDRO CORTES", speeches$who)
    speeches$who <- gsub.e("^GUSTAVO PEDRO CORTES SANTIAGO$", "SANTIAGO GUSTAVO PEDRO CORTES", speeches$who)
    speeches$who <- gsub.e("^GUADALUPE FLORES SALAZAR$", "GUADALUPE SOCORRO FLORES SALAZAR", speeches$who)
    speeches$who <- gsub.e("^GERARDO ESCAROZ SOLER$", "GERARDO ANTONIO ESCAROZ SOLER", speeches$who)
    speeches$who <- gsub.e("LLDEFONSO", "ILDEFONSO", speeches$who)
    speeches$who <- gsub.e("MONRROY", "MONROY", speeches$who)
    speeches$who <- gsub.e("^GUSTAVO CARDENAS$", "GUSTAVO CARDENAS MONROY", speeches$who)
    speeches$who <- gsub.e("GREGORIO BARRADAS MIRAMETE", "GREGORIO BARRADAS MIRAVETE", speeches$who)
    speeches$who <- gsub.e("GERRDO", "GERARDO", speeches$who)
    speeches$who <- gsub.e("GERARDO LAGUNES GALINA", "GERARDO LAGUNES GALLINA", speeches$who)
    speeches$who <- gsub.e("GERARDO AMEZOLA FONSECA", "GERARDO AMEZOLA FONCECA", speeches$who)
    speeches$who <- gsub.e("GABRIELA GONZALES MARTINEZ", "GABRIELA GONZALEZ MARTINEZ", speeches$who)
    speeches$who <- gsub.e("FRANCISCO SANTOS ARREOLA", "FRANCISCO JAVIER SANTOS ARREOLA", speeches$who)
    speeches$who <- gsub.e("^FRANCISCO SANTOS$", "FRANCISCO JAVIER SANTOS ARREOLA", speeches$who)
    speeches$who <- gsub.e("FRANCISCO JAVIER PLASCENCIA ALONZO", "FRANCISCO JAVIER PLASCENCIA ALONSO", speeches$who)
    speeches$who <- gsub.e("^FRANCISCO FRAILE$", "FRANCISCO ANTONIO FRAILE GARCIA", speeches$who)
    speeches$who <- gsub.e("^FRANCISCO DOMINGUEZ$", "FRANCISCO DOMINGUEZ SERVIEN", speeches$who)
    speeches$who <- gsub.e("FERNEL GALVAN RODRIGUEZ", "FERNEL ARTURO GALVEZ RODRIGUEZ", speeches$who)
    speeches$who <- gsub.e("FERNANDO QUETZCOALT MOCTEZUMA PEREDA", "FERNANDO QUETZALCOATL MOCTEZUMA PEREDA", speeches$who)
    speeches$who <- gsub.e("FERNANDO QUETZA.COATL MOCTEZUMA PEREDA", "FERNANDO QUETZALCOATL MOCTEZUMA PEREDA", speeches$who)
    speeches$who <- gsub.e("FERNANDO QUETZALCOATL PEREDA MOCTEZUMA", "FERNANDO QUETZALCOATL MOCTEZUMA PEREDA", speeches$who)
    speeches$who <- gsub.e("^FERNANDO MOCTEZUMA PEREDA$", "FERNANDO QUETZALCOATL MOCTEZUMA PEREDA", speeches$who)
    speeches$who <- gsub.e("^FERNANDO ENRIQUE MAYANS$", "FERNANDO ENRIQUE MAYANS CANABAL", speeches$who)
    speeches$who <- gsub.e("FERNANDA (?:ELVIRA )?.ILLAFRANCA AGUIRRE", "FERNANDA ELVIRA VILLAFRANCA AGUIRRE", speeches$who)
    speeches$who <- gsub.e("FAUSTO (?:FLUVIO )?MENDOZA MALDONADO", "FAUSTO FLAVIO MENDOZA MALDONADO", speeches$who)
    speeches$who <- gsub.e("^FAUSTINO JAVIER GONZALEZ ESTRADA$", "FAUSTINO JAVIER ESTRADA GONZALEZ", speeches$who)
    speeches$who <- gsub.e("^FABIAN MONTES SANCHEZ$", "FABIAN FERNANDO MONTES SANCHEZ", speeches$who)
    speeches$who <- gsub.e("^ESPERANZA ..RELOS BORJA$", "MARIA ESPERANZA MORELOS BORJA", speeches$who)
    speeches$who <- gsub.e("ESMERALDA CARDENAS FONSECA", "ESMERALDA CARDENAS SANCHEZ", speeches$who)
    speeches$who <- gsub.e("ERIKA LA..E..I ..GEL", "ERIKA LARREGUI NAGEL", speeches$who)
    speeches$who <- gsub.e("ERI. LOPEZ BARRIGA", "ERICK LOPEZ BARRIGA", speeches$who)
    speeches$who <- gsub.e("EMILIO FLORES DOMINGUEZ", "EMILIO RAMON RAMIRO FLORES DOMINGUEZ", speeches$who)
    speeches$who <- gsub.e("EMILIO GAMBOA PATRON", "EMILIO ANTONIO GAMBOA PATRON", speeches$who)
    speeches$who <- gsub.e("GUADALUPUE", "GUADALUPE", speeches$who)
    speeches$who <- gsub.e("ELSA GUADALUPE CONDE RODRIGUEZ", "ELSA DE GUADALUPE CONDE RODRIGUEZ", speeches$who)
    speeches$who <- gsub.e("ELMAR DIAZ SOLORZANO", "ELMAR DARINEL DIAZ SOLORZANO", speeches$who)
    speeches$who <- gsub.e("^ELIA ROMERO GUZMAN$", "ROSA ELIA ROMERO GUZMAN", speeches$who)
    speeches$who <- gsub.e("ELIA HERNANDEZ HERNANDEZ", "ELIA HERNANDEZ NUÑEZ", speeches$who)
    speeches$who <- gsub.e("EDUARDO (?:SERGIO )?DE LA TORRES? JARAMILLO", "EDUARDO SERGIO DE LA TORRE JARAMILLO", speeches$who)
    speeches$who <- gsub.e("EDUARDO SANCHEZ ANDRADE", "EDUARDO SANCHEZ HERNANDEZ", speeches$who)
    speeches$who <- gsub.e("^EDUARDO SANCHEZ$", "EDUARDO SANCHEZ HERNANDEZ", speeches$who)
    speeches$who <- gsub.e("EDUARDO ESPINOSA ABUXAPQUI", "EDUARDO ELIAS ESPINOSA ABUXAPQUI", speeches$who)
    speeches$who <- gsub.e("EDUARDO EDUARDO SERGIO", "EDUARDO SERGIO", speeches$who)
    speeches$who <- gsub.e("DOLORES (?:DE MARIA )?MANUELL-GOMEZ ANGULO", "DOLORES DE MARIA MANUELL GOMEZ ANGULO", speeches$who)
    speeches$who <- gsub.e("DOLORES (?:DE MARIA )?MANUELL GOMEZ$", "DOLORES DE MARIA MANUELL GOMEZ ANGULO", speeches$who)
    speeches$who <- gsub.e("DOLORES DE MARIA MANUEL GOMEZ$", "DOLORES DE MARIA MANUELL GOMEZ ANGULO", speeches$who)
    speeches$who <- gsub.e("DIODORO CARRASCO ALTAMIRANO", "DIODORO HUMBERTO CARRASCO ALTAMIRANO", speeches$who)
    speeches$who <- gsub.e("^DIEGO AGUILAR$", "DIEGO AGUILAR ACUÑA", speeches$who)
    speeches$who <- gsub.e("^DAVID MALDONADO$", "DAVID MALDONADO GONZALEZ", speeches$who)
    speeches$who <- gsub.e("DAVID LARA COMPEAN DAVID", "DAVID LARA COMPEAN", speeches$who)
    speeches$who <- gsub.e("CUAUHTEMOC VELASCO OLIVA", "CUAUHTEMOC JESUS VELASCO OLIVA", speeches$who)
    speeches$who <- gsub.e("CRISTIAN CASTAÑO CONTERAS", "CRISTIAN CASTAÑO CONTRERAS", speeches$who)
    speeches$who <- gsub.e("^CHRISTIAN MARTIN LUJANO$", "CHRISTIAN MARTIN LUJANO NICOLAS", speeches$who)
    speeches$who <- gsub.e("^(?:CHARBEL )?JORGE ES?T.FAN CHIDIAC$", "CHARBEL JORGE ESTEFAN CHIDIAC", speeches$who)
    speeches$who <- gsub.e("CESAR HORA.IO DUARTE JAC?QUEZ", "CESAR HORACIO DUARTE JAQUEZ", speeches$who)
    speeches$who <- gsub.e("CESAR HORACIO JAQUEZ DUARTE", "CESAR HORACIO DUARTE JAQUEZ", speeches$who)
    speeches$who <- gsub.e("CESAR DUARTE JAC?QUEZ", "CESAR HORACIO DUARTE JAQUEZ", speeches$who)
    speeches$who <- gsub.e("^CESAR CAMACHO$", "CESAR CAMACHO QUIROZ", speeches$who)
    speeches$who <- gsub.e("CELSO DAVID PULIDO DE SANTIAGO", "CELSO DAVID PULIDO SANTIAGO", speeches$who)
    speeches$who <- gsub.e("CELSO PULIDO SANTIAGO", "CELSO DAVID PULIDO SANTIAGO", speeches$who)
    speeches$who <- gsub.e("CARLOS (?:ALBERTO )?PUENTES? SALAS", "CARLOS ALBERTO PUENTE SALAS", speeches$who)
    speeches$who <- gsub.e("^CARLOS NAVARRO$", "CARLOS NAVARRO LOPEZ", speeches$who)
    speeches$who <- gsub.e("^CARLOS ERNESTO ZATARAIN$", "CARLOS ERNESTO ZATARAIN GONZALEZ", speeches$who)
    speeches$who <- gsub.e("CARLOS ALBERTO NAVARRO SUGUICH", "CARLOS ALBERTO NAVARRO SUGICH", speeches$who)
    speeches$who <- gsub.e("^CHAURAND ARZATE$", "CARLOS CHAURAND ARZATE", speeches$who)
    speeches$who <- gsub.e("^CARLOS ZATARAIN GONZALEZ$", "CARLOS ERNESTO ZATARAIN GONZALEZ", speeches$who)
    speeches$who <- gsub.e("CALOS ROBERTO MARTINEZ MARTINEZ", "CARLOS ROBERTO MARTINEZ MARTINEZ", speeches$who)
    speeches$who <- gsub.e("BENJAMIN GONZALEZ ROARO", "BENJAMIN ERNESTO GONZALEZ ROARO", speeches$who)
    speeches$who <- gsub.e("^BEATRIZ PAGES LLERGO$", "BEATRIZ PAGES LLERGO REBOLLAR", speeches$who)
    speeches$who <- gsub.e("^AURORA CERVANTES$", "AURORA CERVANTES RODRIGUEZ", speeches$who)
    speeches$who <- gsub.e("ATURO MARTINEZ ROCHA", "ARTURO MARTINEZ ROCHA", speeches$who)
    speeches$who <- gsub.e("ARTEMIO GOMEZ TORRES", "ARTEMIO TORRES GOMEZ", speeches$who)
    speeches$who <- gsub.e("ARNULFO (?:ELIAS )?CORDERO ALF?ON.O", "ARNULFO ELIAS CORDERO ALFONZO", speeches$who)
    speeches$who <- gsub.e("ARN.LDO OCHOA (?:GONZALE.|CONTRERAS)", "ARNOLDO OCHOA GONZALEZ", speeches$who)
    speeches$who <- gsub.e("ARMANDO JESUS FELIX OLGUIN", "ARMANDO JESUS FELIX HOLGUIN", speeches$who)
    speeches$who <- gsub.e("^ARMANDO GARCIA$", "ARMANDO GARCIA MENDEZ", speeches$who)
    speeches$who <- gsub.e("ARELY MAS?DRID TOVILLA", "ARELI MADRID TOVILLA", speeches$who)
    speeches$who <- gsub.e("ARACELY ESCALANTE JASSO", "ARACELI ESCALANTE JASSO", speeches$who)
    speeches$who <- gsub.e("^ANTONIO XAVIER LOPEZ$", "ANTONIO XAVIER LOPEZ ADAME", speeches$who)
    speeches$who <- gsub.e("ANTONIO XAVIER JIMENEZ LOPEZ", "ANTONIO XAVIER LOPEZ ADAME", speeches$who)
    speeches$who <- gsub.e("ANTONIO SANCHEZ DIAS DE RIVERA", "ANTONIO SANCHEZ DIAZ DE RIVERA", speeches$who)
    speeches$who <- gsub.e("^ANTONIO MUÑOZ$", "JOSE ANTONIO MUÑOZ SERRANO", speeches$who)
    speeches$who <- gsub.e("ANTONIO JOSE ANTONIO MUÑOZ SERRANO", "JOSE ANTONIO MUÑOZ SERRANO", speeches$who)
    speeches$who <- gsub.e("ANTONIO DIAZ ATHIE", "ANTONIO DE JESUS DIAZ ATHIE", speeches$who)
    speeches$who <- gsub.e("ANOLDO OCHOA GONZALEZ", "ARNOLDO OCHOA GONZALEZ", speeches$who)
    speeches$who <- gsub.e("ANGEL DESCHAMPS FALCON", "ANGEL RAFAEL DESCHAMPS FALCON", speeches$who)
    speeches$who <- gsub.e("ANDRES BERMUDEZ MIRAMONTES", "ANDRES BERMUDEZ VIRAMONTES", speeches$who)
    speeches$who <- gsub.e("ALONSO LIZAOLA DE LA TORRE", "ALONSO MANUEL LIZAOLA DE LA TORRE", speeches$who)
    speeches$who <- gsub.e("ALMA XOCHIT?L CARDONA BENAVIDE.", "ALMA XOCHITL CARDONA BENAVIDEZ", speeches$who)
    speeches$who <- gsub.e("ALMA LILIA LUNA MURGUIA", "ALMA LILIA LUNA MUNGUIA", speeches$who)
    speeches$who <- gsub.e("ALMA EDUVIGES ALCARAZ HERNANDEZ", "ALMA EDWVIGES ALCARAZ HERNANDEZ", speeches$who)
    speeches$who <- gsub.e("^ALMA BENAVIDES$", "ALMA EDWVIGES ALCARAZ HERNANDEZ", speeches$who)
    speeches$who <- gsub.e("^ALFONSO SUAREZ DEL REAL$", "ALFONSO SUAREZ DEL REAL Y AGUILERA", speeches$who)
    speeches$who <- gsub.e("ALFONSO ROLANDO IZQUIERDO BUSTAMENTE", "ALFONSO ROLANDO IZQUIERDO BUSTAMANTE", speeches$who)
    speeches$who <- gsub.e("ALFONSO IZQUIERDO BUSTAMANTE", "ALFONSO ROLANDO IZQUIERDO BUSTAMANTE", speeches$who)
    speeches$who <- gsub.e("ALFONSO BELLO PEREZ", "ALFONSO OTHON BELLO PEREZ", speeches$who)
    speeches$who <- gsub.e("ALEJANDRO ENRIQUE DELGADO ASCOY", "ALEJANDRO ENRIQUE DELGADO OSCOY", speeches$who)
    speeches$who <- gsub.e("ALEIDA ALVAVEZ RUIZ", "ALEIDA ALAVEZ RUIZ", speeches$who)
    speeches$who <- gsub.e("^ALEIDA ALAVEZ$", "ALEIDA ALAVEZ RUIZ", speeches$who)
    speeches$who <- gsub.e("ALBERTO NARCI.O AMADOR LEAL", "NARCISO ALBERTO AMADOR LEAL", speeches$who)
    speeches$who <- gsub.e("ALBERTO AMADOR LEAL NARCIZO", "NARCISO ALBERTO AMADOR LEAL", speeches$who)
    speeches$who <- gsub.e("^ALBERTO AMADOR LEAL$", "NARCISO ALBERTO AMADOR LEAL", speeches$who)
    speeches$who <- gsub.e("ADRIAN PEDRO.. CASTILLO", "ADRIAN PEDROZO CASTILLO", speeches$who)
    speeches$who <- gsub.e("ADRIANA RODRIGUEZ VIZCARRA VELASQUEZ", "ADRIANA RODRIGUEZ VIZCARRA VELAZQUEZ", speeches$who)
    speeches$who <- gsub.e("^ADRIANA RODRIGUEZ VIZCARRA$", "ADRIANA RODRIGUEZ VIZCARRA VELAZQUEZ", speeches$who)
    speeches$who <- gsub.e("ADOLFO HERNANDEZ MOTA", "ADOLFO MOTA HERNANDEZ", speeches$who)
    speeches$who <- gsub.e("ADOLFO ESCOBAR .AR.I.E.", "ADOLFO ESCOBAR JARDINEZ", speeches$who)
    speeches$who <- gsub.e("ADDY JOAQUIN COLDWELL", "ADDY CECILIA JOAQUIN COLDWELL", speeches$who)
    speeches$who <- gsub.e("ABUNDO PEREGRINO GARCIA", "ABUNDIO PEREGRINO GARCIA", speeches$who)
    #speeches$who <- gsub.e("", "", speeches$who)
    ################################
    ## ESTE NO LO ENCUENTRO EN LX ##
    ################################
    speeches$who <- gsub.e("(?:HELIODORO|HERIBERTO) (?:CARLOS )?DIAZ ESCARRAGA", "HELIODORO CARLOS DIAZ ESCARRAGA", speeches$who)
    ## #x
    ## sel.tmp <- grep.e("ROSAEL RAMOS", speeches$who)
    ## speeches$text[(sel.tmp)]
    ## x
    #
    # return manipulation to original data
    tmp.fix[sel.leg,] <- speeches
    speeches <- tmp.fix # restore name
    rm(tmp.fix,sel.leg)
}


