    speeches$who <- gsub.e("El diputado El diputado" , "El diputado", speeches$who)
    speeches$who <- gsub.e("Salador Arellano" , "Salvador Arellano", speeches$who)
    speeches$who <- gsub.e("King de la Rosa" , "King De la Rosa", speeches$who)
    speeches$who <- gsub.e("Raimundo King" , "Raymundo King", speeches$who)
    speeches$who <- gsub.e("Oswaldo Ochoa Gallegos Williams" , "Williams Oswaldo Ochoa Gallegos", speeches$who)
    speeches$who <- gsub.e("Núñez Monreal Magdalena del Socorro" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Micher Camarena" , "Mícher Camarena", speeches$who)
    speeches$who <-   gsub("[YJ]azm[íi]n de los Angeles [Cc]opete Zapot" , "Yazmín de los Angeles Copete Zapot", speeches$who)
    speeches$who <- gsub.e("Zúniga" , "Zúñiga", speeches$who)
    speeches$who <- gsub.e("Zuleyma Hudibro González" , "Zuleyma Huidobro González", speeches$who)
    speeches$who <- gsub.e("William Renan Sosa" , "William Renán Sosa", speeches$who)
    speeches$who <- gsub.e("Víctor Raymundo Nájera" , "Víctor Reymundo Nájera", speeches$who)
    speeches$who <- gsub.e("Rafael González Manrique" , "Rafael González Manríquez", speeches$who)
    speeches$who <- gsub.e("Verónica Beatríz" , "Verónica Beatriz", speeches$who)
    speeches$who <- gsub.e("Jesús Mujica Morga" , "Jesús Mojica Morga", speeches$who)
    speeches$who <- gsub.e("Taya Rellstab" , "Tanya Rellstab", speeches$who)
    speeches$who <- gsub.e("Tanya Rellstab Carreto" , "Tanya Rellstab", speeches$who) # there must be a better way
    speeches$who <- gsub.e("Tanya Rellstab" , "Tanya Rellstab Carreto", speeches$who) # there must be a better way
    speeches$who <- gsub.e("Roxana Luna Portillo" , "Roxana Luna Porquillo", speeches$who)
    speeches$who <- gsub.e("Villareal" , "Villarreal", speeches$who)
    speeches$who <- gsub.e("Mej[ií]a Berdejas?" , "Mejía Berdeja", speeches$who)
    speeches$who <- gsub.e("García Berdeja" , "Mejía Berdeja", speeches$who)
    speeches$who <- gsub.e("Ricardo Avila Monreal" , "Ricardo Monreal Avila", speeches$who)
    speeches$who <- gsub.e("Ricardo Anaya Cortéz" , "Ricardo Anaya Cortés", speeches$who)
    speeches$who <- gsub.e("René Fujiwara Montelongo" , "René Ricardo Fujiwara Montelongo", speeches$who)
    speeches$who <- gsub.e("Regina Vázquez" , "Regina Vázquez Saut", speeches$who)
    speeches$who <- gsub.e("Raquel Jiménez Cerillo" , "Raquel Jiménez Cerrillo", speeches$who)
    speeches$who <- gsub.e("Resendiz" , "Reséndiz", speeches$who)
    speeches$who <- gsub.e("Peña Rocío" , "Peña Recío", speeches$who)
    speeches$who <- gsub.e("Nestor Octavio" , "Néstor Octavio", speeches$who)
    speeches$who <- gsub.e("Meri?lyn Gómez Poz[oa]s" , "Merilyn Gómez Pozos", speeches$who)
    speeches$who <- gsub.e("Mayra Robles Aguirre" , "Mayra Karina Robles Aguirre", speeches$who)
    speeches$who <- gsub.e("Vázquez Villanueva" , "Vásquez Villanueva", speeches$who)
    speeches$who <- gsub.e("Mario Sánchez Ruíz" , "Mario Sánchez Ruiz", speeches$who)
    speeches$who <- gsub.e("María del Rosario Fátima Pariente Gavito" , "María del Rosario de Fátima Pariente Gavito", speeches$who)
    speeches$who <- gsub.e("Carmen Martínez Santillana" , "Carmen Martínez Santillán", speeches$who)
    speeches$who <- gsub.e("Ramírez Díez Gutiérrez" , "Ramírez Diez Gutiérrez", speeches$who)
    speeches$who <- gsub.e("Margarita Elena Tapia Fonllem" , "emm-temporal", speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Elena Tapia Fonllem" , "Margarita Elena Tapia Fonllem", speeches$who)     # there must be a better way
    speeches$who <- gsub.e("Margarita Tapia Fonllem" , "Margarita Elena Tapia Fonllem", speeches$who) # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Margarita Elena Tapia Fonllem" , speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Margarita Elena Tapia Fonllem" , "emm-temporal", speeches$who)       # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Margarita Elena Tapia Fonllem" , speeches$who)       # there must be a better way
    speeches$who <- gsub.e("Manilo Fabio" , "Manlio Fabio", speeches$who)
    speeches$who <- gsub.e("Magdalena Núñez Monreal" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Ma Elena Cano Ayala" , "María Elena Cano Ayala", speeches$who)
    speeches$who <- gsub.e("Luis María Alcalde Luján" , "Luisa María Alcalde Luján", speeches$who)
    speeches$who <- gsub.e("Garfías Gutiérrez" , "Garfias Gutiérrez", speeches$who)
    speeches$who <- gsub.e("Loret.a (?:Ort[íi]z|Ruiz) Ahlf" , "Loretta Ortiz Ahlf", speeches$who)
    speeches$who <- gsub.e("Loreni?a Iveth Valles? Samperio" , "Lorenia Iveth Valles Sampedro", speeches$who)
    speeches$who <- gsub.e("Athie Flores" , "Athié Flores", speeches$who)
    speeches$who <- gsub.e("Julisa Mejía Guajardo" , "Julisa Mejía Guardado", speeches$who)
    speeches$who <- gsub.e("Judith Magdalena Guerrero López" , "Judit Magdalena Guerrero López", speeches$who)
    speeches$who <-   gsub("Juan francisco" , "Juan Francisco", speeches$who)
    speeches$who <- gsub.e("J. Pilar Montenegro Montoya" , "J. Pilar Moreno Montoya", speeches$who)
    speeches$who <- gsub.e("Quiróga" , "Quiroga", speeches$who)
    speeches$who <- gsub.e("José Manzur Quiroga" , "José Sergio Manzur Quiroga", speeches$who)
    speeches$who <- gsub.e("Federico José González Luna Bueno" , "emm-temporal", speeches$who) # there must be a better way
    speeches$who <- gsub.e("José González$" , "José González Morfín", speeches$who)            # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Federico José González Luna Bueno", speeches$who)  # there must be a better way
    speeches$who <- gsub.e("López Candido" , "López Cándido", speeches$who)
    speeches$who <- gsub.e("León Mendivil" , "León Mendívil", speeches$who)
    speeches$who <- gsub.e("Botello Méndez" , "Botello Montes", speeches$who)
    speeches$who <- gsub.e("Jorge Iván Villalobos Sánchez" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Murilla Karam" , "Murillo Karam", speeches$who)
    speeches$who <- gsub.e("Jéssica Salazar" , "Jessica Salazar", speeches$who)
    speeches$who <- gsub.e("Jazmin" , "Jazmín", speeches$who)
    speeches$who <- gsub.e("[JY]azm[ií]n(?: de los Angeles)? Copete Zapot" , "Yazmín de los Angeles Copete Zapot", speeches$who)
    speeches$who <- gsub.e("Héctor Hugo R[eo]ble[dr]o Gordillo" , "Héctor Hugo Roblero Gordillo", speeches$who)
    speeches$who <- gsub.e("Eligio Cuitláhuac González Farías" , "emm-temporal", speeches$who)    # there must be a better way
    speeches$who <- gsub.e("González Farías" , "Eligio Cuitláhuac González Farías", speeches$who) # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Eligio Cuitláhuac González Farías" , speeches$who)    # there must be a better way
    speeches$who <- gsub.e("Gisela Mota Ocampo" , "Gisela Raquel Mota Ocampo", speeches$who)
    speeches$who <- gsub.e("Albarran" , "Albarrán", speeches$who)
    speeches$who <- gsub.e("Cortazar" , "Cortázar", speeches$who)
    speeches$who <- gsub.e("Cárdenas Guizar" , "Cárdenas Guízar", speeches$who)
    speeches$who <- gsub.e("Francisco Alonso Durazo" , "Francisco Alfonso Durazo", speeches$who)
    speeches$who <-   gsub("Francisco Agustín [Aa]rro[yl]l?o Vieye?ra" , "Francisco Agustín Arroyo Vieyra", speeches$who)
    speeches$who <- gsub.e("Francisca Elena Corrales Corrales" , "emm-temporal", speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Francisca Elena Corrales", "Francisca Elena Corrales Corrales", speeches$who) # there must be a better way
    speeches$who <- gsub.e("emm-temporal", "Francisca Elena Corrales Corrales" , speeches$who)            # there must be a better way
    speeches$who <- gsub.e("Salgado[(]" , "Salgado", speeches$who)
    speeches$who <- gsub.e("Bibriesca Sahagún" , "Bribiesca Sahagún", speeches$who)
    speeches$who <- gsub.e("Belauzarán" , "Belaunzarán", speeches$who)
    speeches$who <- gsub.e("Fernando Alejandro Larraz[aá]bal (?:Bretón|Betrón)" , "Fernando Alejandro Larrazabal Bretón", speeches$who)
    speeches$who <- gsub.e("Federico González Luna Bueno" , "Federico José González Luna Bueno", speeches$who)
    speeches$who <-   gsub("robledo Leal" , "Robledo Leal", speeches$who)
    speeches$who <- gsub.e("Rom[aá]n Qui[aá]n" , "Román Quian", speeches$who)
    speeches$who <- gsub.e("Dora María Talamante Lemas" , "Dora María Guadalupe Talamante Lemas", speeches$who)
    speeches$who <- gsub.e("Diego Sinhue" , "Diego Sinhué", speeches$who)
    speeches$who <- gsub.e("Barcenas Nieves" , "Bárcenas Nieves", speeches$who)
    speeches$who <- gsub.e("Pérez Tejeda Padilla" , "Pérez Tejada Padilla", speeches$who)
    speeches$who <- gsub.e("Dario Zacarías Capuchino" , "Darío Zacarías Capuchino", speeches$who)
    speeches$who <- gsub.e("Ruíz" , "Ruiz", speeches$who)
    speeches$who <-   gsub("[CD]uarte Or[dt]uño" , "Duarte Ortuño", speeches$who)
    speeches$who <- gsub.e("Carmen Lucia" , "Carmen Lucía", speeches$who)
    speeches$who <- gsub.e("Carlos de Jesús Alejandro" , "Carlos De Jesús Alejandro", speeches$who)
    speeches$who <- gsub.e("Sttefan" , "Steffan", speeches$who)
    speeches$who <- gsub.e("Antonio Altamirano Carol" , "Carol Antonio Altamirano", speeches$who)
    speeches$who <- gsub.e("Amira Griselda" , "Amira Gricelda", speeches$who)
    speeches$who <- gsub.e("Amilcar" , "Amílcar", speeches$who)
    speeches$who <- gsub.e("All?iet Mariana Bautista (?:Bravo|López)" , "Alliet Mariana Bautista Bravo", speeches$who)
    speeches$who <- gsub.e("Alicia Ricalde Magaña" , "Alicia Concepción Ricalde Magaña", speeches$who)
    speeches$who <- gsub.e("Alfonso Montaño" , "Alfonso Inzunza Montaño", speeches$who)
    speeches$who <- gsub.e("Alejandro Carvajal[.] González" , "Alejandro Carbajal González", speeches$who)
    speeches$who <- gsub.e("Aida Fabiola" , "Aída Fabiola", speeches$who)
    speeches$who <- gsub.e("Adolfo Oribe Bellinger" , "Adolfo Orive Bellinger", speeches$who)
                                        #
    speeches$who <- gsub.e("Xavier A[xz]uara (?:Zúñiga|Núñez)" , "Xavier Azuara Zúñiga", speeches$who)
    speeches$who <- gsub.e("William Oswaldo Ochoa" , "Williams Oswaldo Ochoa", speeches$who)
    speeches$who <- gsub.e("Víctor Rafael Manríquez González" , "Víctor Rafael González Manríquez", speeches$who)
    speeches$who <- gsub.e("Víctor Oswaldo Sol[ií]s" , "Víctor Oswaldo Fuentes Solís", speeches$who)
    speeches$who <- gsub.e("Víctor Manuel Manriquez González" , "Víctor Manuel Manríquez González", speeches$who)
    speeches$who <- gsub.e("Víctor Jorrín Lozano" , "Víctor Humberto Jorrín Lozano", speeches$who)
    speeches$who <- gsub.e("Ulíses" , "Ulises", speeches$who)
    speeches$who <- gsub.e("Tomás Torres Marcado" , "Tomás Torres Mercado", speeches$who)
    speeches$who <-   gsub("Silvano [Bb]lan[cd]o de Deaquino" , "Silvano Blanco Deaquino", speeches$who)
    speeches$who <-   gsub("Silvano [Aa]ureoles [Cc]onejo" , "Silvano Aureoles Conejo", speeches$who)
    speeches$who <-   gsub("Sergio [Aa]ugusto Chan Lugo" , "Sergio Augusto Chan Lugo", speeches$who)
    speeches$who <- gsub.e("Núñez Monreal Magdalena del Socorro" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Secretaría Magdalena del Socorro Núñez" , "Magdalena del Socorro Núñez", speeches$who)
    speeches$who <- gsub.e("Sebastián(?: Alfonso)? de la Rosa Peláez" , "Sebastián Alfonso De la Rosa Peláez", speeches$who)
    speeches$who <- gsub.e("Ortíz" , "Ortiz", speeches$who)
    speeches$who <- gsub.e("Salgad$" , "Salgado", speeches$who)
    speeches$who <- gsub.e("Olguín" , "Olguín", speeches$who)
    speeches$who <- gsub.e("Chávez Conteras" , "Chávez Contreras", speeches$who)
    speeches$who <- gsub.e("Morneal" , "Monreal", speeches$who)
    speeches$who <-   gsub("Ricardo Anaya [Cc]ort[eé]s?" , "Ricardo Anaya Cortés", speeches$who)
    speeches$who <- gsub.e("Fijiwara" , "Fujiwara", speeches$who)
    speeches$who <- gsub.e("Saut Saut" , "Saut", speeches$who)
    speeches$who <- gsub.e("Raúl Paz Alonso" , "Raúl Paz Alonzo", speeches$who)
    speeches$who <- gsub.e("Raquel Jiménez Carrillo" , "Raquel Jiménez Cerrillo", speeches$who)
    speeches$who <- gsub.e("Patricia Guadalupe Peña Recío" , "Patricia Guadalupe Peña Recio", speeches$who)
    speeches$who <- gsub.e("Pacheco Rodríguez Ricardo Fidel" , "Ricardo Fidel Pacheco Rodríguez", speeches$who)
    speeches$who <- gsub.e("Merilyn Gómez Posos" , "Merilyn Gómez Pozos", speeches$who)
    speeches$who <- gsub.e("Martín Heredia Lizárraga" , "Martín Alonso Heredia Lizárraga", speeches$who)
    speeches$who <- gsub.e("Martín Alfonso Heredia Lizárraga" , "Martín Alonso Heredia Lizárraga", speeches$who)
    speeches$who <- gsub.e("Martha Beatriz Córdoba Bernal" , "Martha Beatriz Córdova Bernal", speeches$who)
    speeches$who <- gsub.e("Mario Guillén Guillén" , "Mario Francisco Guillén Guillén", speeches$who)
    speeches$who <- gsub.e("Maribel Henríquez Ramírez" , "Maribel Enríquez Ramírez", speeches$who)
    speeches$who <- gsub.e("María del Rocio" , "María del Rocio", speeches$who)
    speeches$who <- gsub.e("María del Carmen Guzmán Urbán" , "María del Carmen Guzmán Urban", speeches$who)
    speeches$who <- gsub.e("Mar[ií]a de las? Nieves Garc[íi]a$" , "María de las Nieves García Fernández", speeches$who)
    speeches$who <-   gsub("[Tt]orres Cofi[ñn]o" , "Torres Cofiño", speeches$who)
    speeches$who <- gsub.e("Marcelo de Jesús Torres$" , "Marcelo de Jesús Torres Cofino", speeches$who)
    speeches$who <- gsub.e("Fabio Beltrones Rivero" , "Fabio Beltrones Rivera", speeches$who)
    speeches$who <- gsub.e("Manlio Fabio Beltrones$" , "Manlio Fabio Beltrones Rivera", speeches$who)
    speeches$who <- gsub.e("Madalena del Socorro Núñez Monreal" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("González Roldan" , "González Roldán", speeches$who)
    speeches$who <- gsub.e("Luis Angel Espinosa Cházaro" , "Luis Angel Xariel Espinosa Cházaro", speeches$who)
    speeches$who <- gsub.e("Alcalde Lujan" , "Alcalde Luján", speeches$who)
    speeches$who <- gsub.e("Luis Alberto Villarreal$" , "Luis Alberto Villarreal García", speeches$who)
    speeches$who <- gsub.e("Loreni?a .veth Valles? Sampedro" , "Lorenia Yveth Valles Sampedro", speeches$who)
    speeches$who <- gsub.e("Leopoldo Sánchez Ruz" , "Leopoldo Sánchez Cruz", speeches$who)
    speeches$who <-   gsub("Julio C[ée]sar Moreno [Rr]ivera" , "Julio César Moreno Rivera", speeches$who)
    speeches$who <- gsub.e("Cesar Lorenzini" , "César Lorenzini", speeches$who)
    speeches$who <- gsub.e("Juan Fran?cisco Cá[cz][ae]res de la Fuente" , "Juan Francisco Cáceres de la Fuente", speeches$who)
    speeches$who <-   gsub("Juan [Bb]ueno Torio" , "Juan Bueno Torio", speeches$who)
    speeches$who <- gsub.e("J[.] Pilar Moreno Montoya" , "José Pilar Moreno Montoya", speeches$who)
    speeches$who <- gsub.e("José Luis Val$" , "José Luis Valle Magaña", speeches$who)
    speeches$who <- gsub.e("José Luis Muños Soria" , "José Luis Muñoz Soria", speeches$who)
    speeches$who <- gsub.e("José Luis Martínez Martínez" , "José Luis Márquez Martínez", speeches$who) # OJO: podría tbn ser Mtz Meléndez (suplente)
    speeches$who <- gsub.e("José Guillermo Amaya" , "José Guillermo Anaya", speeches$who)
    speeches$who <- gsub.e("(?:presidente )?José González Morf?[ií]n( Morf?[ií]n)?" , "José González Morfín", speeches$who)
    speeches$who <- gsub.e("presidente " , "", speeches$who)
    speeches$who <- gsub.e("Víctor Manuel Jorrín Serrano" , "Víctor Manuel Jorrín Lozano", speeches$who)
    speeches$who <- gsub.e("Víctor Humberto Jorrín Lozano" , "Víctor Manuel Jorrín Lozano", speeches$who)
    speeches$who <-   gsub("Silvano [Bb]lan[cd]o Deaquino" , "Silvano Blanco Deaquino", speeches$who)
    speeches$who <- gsub.e("Sergio Chan Lugo" , "Sergio Augusto Chan Lugo", speeches$who)
    speeches$who <- gsub.e("Ruben Acosta Montoya" , "Rubén Acosta Montoya", speeches$who)
    speeches$who <- gsub.e("Roy Angel Gómez Olguín" , "Roy Argel Gómez Olguín", speeches$who)
    speeches$who <-   gsub("Manuel rafael" , "Manuel Rafael", speeches$who)
    speeches$who <- gsub.e("Ladón de Guevara" , "Ladrón de Guevara", speeches$who)
    speeches$who <- gsub.e("^Manuel Huerta Ladrón" , "Manuel Rafael Huerta Ladrón", speeches$who) # there must be a better way
    speeches$who <-   gsub("Manuel Rafael [Hh]uert?a Ladrón de Guevara" , "Manuel Rafael Huerta Ladrón de Guevara", speeches$who)
    speeches$who <-   gsub("Rafael Manuel Huerta Ladrón de Guevara" , "Manuel Rafael Huerta Ladrón de Guevara", speeches$who)
    speeches$who <- gsub.e("Carpinteyro Caderón" , "Carpinteyro Calderón", speeches$who)
    speeches$who <-  sub.e("^.+El diputado Martín Alonso Heredia Lizárraga, la diputada Lizbeth Eugenia Rosas Montero, el diputado Luis Antonio González Roldán</b>: Sí, protesto.*$" , "varios-protestan-Mesa-Directiva", speeches$who)
    speeches$who <- gsub.e("Omar Borboa Becerra" , "Omar Antonio Borboa Becerra", speeches$who)
    speeches$who <- gsub.e("Mar[tí]h?a Beatriz Zavala Peniche" , "Beatriz Zavala Peniche", speeches$who)
    speeches$who <- gsub.e("Dunyasca" , "Dunyaska", speeches$who)
    speeches$who <- gsub.e("Mar[íi]a del Roc[íi]o" , "María del Rocío", speeches$who)
    speeches$who <- gsub.e("María de la Nieves García$" , "María de la Nieves García Fernández", speeches$who)
    speeches$who <- gsub.e("María Carmen Segura López" , "María Carmen López Segura", speeches$who)
    speeches$who <- gsub.e("Fonllen" , "Fonllem", speeches$who)
    speeches$who <- gsub.e("Marco Rosendo Medina Filigrana" , "Marcos Rosendo Medina Filigrana", speeches$who)
    speeches$who <-   gsub("Medina filigrana" , "Medina Filigrana", speeches$who)
    speeches$who <- gsub.e("^Rosendo(?: Marcos)? Medina Filigrana" , "Marcos Rosendo Medina Filigrana", speeches$who)
    speeches$who <- gsub.e("Cofño" , "Cofiño", speeches$who)
    speeches$who <- gsub.e("Cofino" , "Cofiño", speeches$who)
    speeches$who <- gsub.e("Magdalena del Socorro Núñez$" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Luis Alberto González Roldán" , "Luis Antonio González Roldán", speeches$who)
    speeches$who <- gsub.e("Loretra Ortiz Half" , "Loretta Ortiz Half", speeches$who)
    speeches$who <- gsub.e("Li[zs]beth Eugenia Rosas (?:Montero|Moreno)" , "Lizbeth Eugenia Rosas Montero", speeches$who)
    speeches$who <- gsub.e("Laura Jiménez Martel Cantú" , "Laura Ximena Martel Cantú", speeches$who)
    speeches$who <- gsub.e("Julissa Mejía Guardado" , "Julisa Mejía Guardado", speeches$who)
    speeches$who <- gsub.e("José Sergio Quiroga Manzur" , "José Sergio Manzur Quiroga", speeches$who)
    speeches$who <- gsub.e("José Everardo Gómez Nava" , "José Everardo Nava Gómez", speeches$who)
    speeches$who <- gsub.e("José Angelino Caamal Méndez" , "José Angelino Caamal Mena", speeches$who)
    speeches$who <- gsub.e("Benavidez Castañeda" , "Benavides Castañeda", speeches$who)
    speeches$who <- gsub.e("Jorge Iván Villalobos Seánez" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Jorge Iván Seáñez Villalobos" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Sotomayor Cháve$" , "Sotomayor Chávez", speeches$who)
    speeches$who <- gsub.e("Jesús Tolentito" , "Jesús Tolentino", speeches$who)
    speeches$who <- gsub.e("Homero Ricardo Niño de Rivera Val" , "Homero Ricardo Niño de Rivera Vela", speeches$who)
    speeches$who <- gsub.e("Heriberto Galindo Quiñones" , "Heriberto Manuel Galindo Quiñones", speeches$who)
    speeches$who <- gsub.e("Héctor Irineo Mares Cossío" , "Héctor Ireneo Mares Cossío", speeches$who)
    speeches$who <- gsub.e("Héctor Gutiérrez de la Garza" , "Héctor Humberto Gutiérrez de la Garza", speeches$who)
    speeches$who <- gsub.e("Graciela Saldaña Freire" , "Graciela Saldaña Fraire", speeches$who)
    speeches$who <- gsub.e("Gloria Saldaña Fraire" , "Graciela Saldaña Fraire", speeches$who)
    speeches$who <- gsub.e("Gerardo Villanueva Albarán" , "Gerardo Villanueva Albarrán", speeches$who)
    speeches$who <- gsub.e("Gavilán Rodolfo Dorador Pérez" , "Rodolfo Dorador Pérez Gavilán", speeches$who)
    speeches$who <- gsub.e("Francisco Antonio Mora Molina" , "Francisco Antonio Eduardo Mora Molina", speeches$who)
    speeches$who <- gsub.e("Francisco Antonio Durazo Montaño" , "Francisco Alfonso Durazo Montaño", speeches$who)
    speeches$who <- gsub.e("Francisco Alberto Cepeda González" , "Francisco Alberto Zepeda González", speeches$who)
    speeches$who <- gsub.e("^francisco" , "Francisco", speeches$who)
    speeches$who <- gsub.e("Fernando Zarate Salgado" , "Fernando Zárate Salgado", speeches$who)
    speeches$who <- gsub.e("de las Fuetes Hernández" , "de las Fuentes Hernández", speeches$who)
    speeches$who <- gsub.e("Fernando Charles Hernández" , "Fernando Charleston Hernández", speeches$who)
    speeches$who <- gsub.e("Muños Kapamas" , "Muñoz Kapamas", speeches$who)
    speeches$who <- gsub.e("Ernesto Germán Sánchez Gutiérrez" , "Ernesto Germán Sánchez Jiménez", speeches$who)
    speeches$who <- gsub.e("Erica del Carmen Velázquez Vacío" , "Erica del Carmen Velázquez Vacio", speeches$who)
    speeches$who <- gsub.e("Enrique Palomino Aubry de Castro" , "Enrique Aubry de Castro Palomino", speeches$who)
    speeches$who <- gsub.e("Eligio Cuitláhuac González Farías" , "Eligio Cuitláhuac González Farias", speeches$who)
    speeches$who <- gsub.e("El diputado Manuel" , "Manuel", speeches$who)
    speeches$who <- gsub.e("Dunia Eliane Preciado de la Vega" , "Dunia Eliane de la Vega Preciado", speeches$who)
    speeches$who <- gsub.e("Duna Eliane de la Vega Preciado" , "Dunia Eliane de la Vega Preciado", speeches$who)
    speeches$who <- gsub.e("David Pérez de Tejada Padilla" , "David Pérez Tejada Padilla", speeches$who)
    speeches$who <- gsub.e("Dario Zacarias Capuchino" , "Darío Zacarías Capuchino", speeches$who)
    speeches$who <- gsub.e("Danner González Roldán" , "Danner González Rodríguez", speeches$who)
    speeches$who <- gsub.e(" Damián Vidales Zepeda" , " Damián Zepeda Vidales", speeches$who)
    speeches$who <- gsub.e("Claudia Elena Aguila Torre$" , "Claudia Elena Aguila Torres", speeches$who)
    speeches$who <- gsub.e("Cinth.a Valladares Couoh" , "Cinthya Noemí Valladares Couoh", speeches$who)
    speeches$who <- gsub.e("Chantal Zepeda Escobar" , "Shantall Zepeda Escobar", speeches$who)
    speeches$who <- gsub.e("César Reynaldo Navarro de Alva" , "César Reynaldo Navarro de Alba", speeches$who)
    speeches$who <- gsub.e("Carlos Octavio Castellanos$" , "Carlos Octavio Castellanos Mijares", speeches$who)
    speeches$who <- gsub.e("Carlos Octavio Castellano Mijares" , "Carlos Octavio Castellanos Mijares", speeches$who)
    speeches$who <- gsub.e("Carlos Fernando Augusto Parra" , "Carlos Fernando Angulo Parra", speeches$who)
    speeches$who <- gsub.e("Borges Pasos Teresita de Jesús" , "Teresita de Jesús Borges Pasos", speeches$who)
    speeches$who <- gsub.e("Bonilla Jaime Juana" , "Juana Bonilla Jaime", speeches$who)
    speeches$who <- gsub.e("Bárbara Graciela Romo Fonseca" , "Bárbara Gabriela Romo Fonseca", speeches$who)
    speeches$who <- gsub.e("Aurora Aguilar Rodríguez" , "Aurora de la Luz Aguilar Rodríguez", speeches$who)
    speeches$who <- gsub.e("Arturo Escobar Vega" , "Arturo Escobar y Vega", speeches$who)
    speeches$who <- gsub.e("Arel[iy] Madrid [PT]ovilla" , "Areli Madrid Tovilla", speeches$who)
    speeches$who <- gsub.e("Antonio Astiazarán Gutiérrez" , "Antonio Francisco Astiazarán Gutiérrez", speeches$who)
    speeches$who <- gsub.e("Angulo Parra Carlos Fernando" , "Carlos Fernando Angulo Parra", speeches$who)
    speeches$who <- gsub.e("Angélica Rocío Melchor Vázquez" , "Angélica Rocío Melchor Vásquez", speeches$who)
    speeches$who <- gsub.e("Amalia García Medina" , "Amalia Dolores García Medina", speeches$who)
    speeches$who <- gsub.e("Alliet Bautista Bravo" , "Alliet Mariana Bautista Bravo", speeches$who)
    speeches$who <- gsub.e("Alfredo Maldonado Hernández" , "Alfredo Rivadeneyra Hernández", speeches$who)
    speeches$who <- gsub.e("Alfonso Inzunza Montaño" , "Alfonso Inzunza Montoya", speeches$who)
    speeches$who <- gsub.e("$Alfonso Durazo Montaño" , "Alfonso Francisco Durazo Montaño", speeches$who)
    speeches$who <- gsub.e("Alberto Escamilla Cerón" , "Alberto Leónides Escamilla Cerón", speeches$who)
    speeches$who <- gsub.e("Aceves y del Olmo Carlos Humberto" , "Carlos Humberto Aceves y del Olmo", speeches$who)
    speeches$who <- gsub.e("Loretta Ortiz Half" , "Loretta Ortiz Ahlf", speeches$who)
    speeches$who <- gsub.e("Claudia Elena Aguila Flores" , "Claudia Elena Aguila Torres", speeches$who)
    speeches$who <- gsub.e("Lizbeth Rosas Montero" , "Lizbeth Eugenia Rosas Montero", speeches$who)
    speeches$who <- gsub.e("Juan Marcos Issa Salomón" , "Salomón Juan Marcos Issa", speeches$who)
    speeches$who <- gsub.e("María de Carmen Martínez Santillán" , "María del Carmen Martínez Santillán", speeches$who)
    speeches$who <- gsub.e("María Fernando Romero Lozano" , "María Fernanda Romero Lozano", speeches$who)
    speeches$who <- gsub.e("Alfonso Francisco Durazo Montaño" , "Francisco Alfonso Durazo Montaño", speeches$who)
    speeches$who <- gsub.e("Francisco Zepeda González" , "Francisco Alberto Zepeda González", speeches$who)
    speeches$who <- gsub.e("Fernando Alfredo Rivadeneyra Hernández" , "Alfredo Rivadeneyra Hernández", speeches$who)
    speeches$who <- gsub.e("María Concepción Navarrete Vital" , "Ma. Concepción Navarrete Vital", speeches$who)
    speeches$who <- gsub.e("Cinthya Noem. Valladares Couoh" , "Cinthya Noemy Valladares Couoh", speeches$who)
    speeches$who <- gsub.e("María Guadalupe Mondragón González" , "Ma. Guadalupe Mondragón González", speeches$who)
    speeches$who <- gsub.e("Miguel Agustín Alonso Raya" , "Agustín Miguel Alonso Raya", speeches$who)
    speeches$who <- gsub.e("María Leticia Mendoza Curiel" , "Ma. Leticia Mendoza Curiel", speeches$who)
    speeches$who <- gsub.e("Víctor Hugo Roblero Gordillo" , "Héctor Hugo Roblero Gordillo", speeches$who)
    speeches$who <- gsub.e("Williams Oswaldo Ochoa Gallegos" , "Willy Ochoa Gallegos", speeches$who)
    speeches$who <- gsub.e("Frine Soraya Córdova Morán" , "Frine Soraya Córdoba Morán", speeches$who)
    speeches$who <- gsub.e("María del Socorro Núñez Monreal" , "Magdalena del Socorro Núñez Monreal", speeches$who)
    speeches$who <- gsub.e("Palomino Enrique Aubry De Castro" , "Enrique Aubry De Castro Palomino", speeches$who)
    speeches$who <- gsub.e("María Teresa de Jesús Mojica Morga" , "Teresa de Jesús Mojica Morga", speeches$who)
    speeches$who <- gsub.e("Faustino Félix Chávez" , "Faustino Francisco Félix Chávez", speeches$who)
    speeches$who <- gsub.e("Lorenia Yveth Valles Sampedro" , "Lorenia Iveth Valles Sampedro", speeches$who)
    speeches$who <- gsub.e("Dora María Guadalupe Talamante Lemas" , "Dora María Guadalupe Talamanto Lemas", speeches$who)
    speeches$who <- gsub.e("" , "", speeches$who)
    sel2 <- grep.e("Barbosa Huerta", speeches$who) # Es un senador en sesión congreso general
    speeches$role[sel2] <- speeches$who[sel2] <- "senador"
    speeches$who <- gsub.e("Francisco Elena Corrales Corrales" , "Francisca Elena Corrales Corrales", speeches$who)
    speeches$who <- gsub.e("Elena Francisca Corrales Corrales" , "Francisca Elena Corrales Corrales", speeches$who)
    speeches$who <- gsub.e("César Augusto Chan Lugo" , "Sergio Augusto Chan Lugo", speeches$who)
    speeches$who <- gsub.e("Mar.a( de)? Mont?serrat Baeza Vallejo" , "María de Monserrat Baeza Vallejo", speeches$who)
    speeches$who <- gsub.e("Linda Marina Dolores Munive Temoltzin" , "Linda Marina Dolores Munive Tenoltzin", speeches$who)
    speeches$who <- gsub.e("Cristian Manuel Narváez Romero" , "Christian Manuel Narváez Romero", speeches$who)
    speeches$who <- gsub.e("Erwin Francisco Arriola Doroteo" , "Erwin Francisco Arreola Doroteo", speeches$who)
    speeches$who <- gsub.e("L[íi]lia[nm] Mara Flores Ortega( Rodr.guez)?" , "Líliam Mara Flores Ortega", speeches$who)
    speeches$who <- gsub.e("María Merced León Andablo" , "Ma. Merced León Andablo", speeches$who)
    speeches$who <- gsub.e("María Guadalupe Jaramillo Villa" , "Ma. Guadalupe Jaramillo Villa", speeches$who)
    speeches$who <- gsub.e("María Lucrecia Arzola God.nez" , "María Lucrecia Arzola Godines", speeches$who)
    speeches$who <- gsub.e("María Margarita García Rojas" , "Mariana Dunyaska García Rojas", speeches$who)
    speeches$who <- gsub.e("Lucía Rosales Villegas" , "Lucía Rosales Villega", speeches$who)
    speeches$who <- gsub.e("Carlos Alberto Aceves y Del Olmo" , "Carlos Humberto Aceves y Del Olmo", speeches$who)
    speeches$who <- gsub.e("Marilyn Gómez Pozos" , "Merilyn Gómez Pozos", speeches$who)
    speeches$who <- gsub.e("José Antonio González Roldán" , "Luis Antonio González Roldán", speeches$who)
    speeches$who <- gsub.e("Fernando Maldonado Hernández" , "Fernando Alfredo Maldonado Hernández", speeches$who)
    speeches$who <- gsub.e("Diana Carina Velázquez" , "Diana Karina Velázquez Ramírez", speeches$who)
    speeches$who <- gsub.e("Gerardo Hernández Tapia" , "Gerardo Xavier Hernández Tapia", speeches$who)
    speeches$who <- gsub.e("Jorge Villalobos Seáñez" , "Jorge Iván Villalobos Seáñez", speeches$who)
    speeches$who <- gsub.e("Consuelo Argüelles Loyola" , "Consuelo Argüelles Loya", speeches$who)
    speeches$who <- gsub.e("Carlos Guzmán Cervantes" , "Carlos Bernardo Guzmán Cervantes", speeches$who)
    speeches$who <- gsub.e("Miguel Alonso Heredia Lizárraga" , "Martín Alonso Heredia Lizárraga", speeches$who)
    speeches$who <- gsub.e("Robert López Suárez" , "Roberto López Suárez", speeches$who)
    speeches$who <- gsub.e("Víctor Díaz Palacios" , "Víctor Emanuel Díaz Palacios", speeches$who)
    speeches$who <- gsub.e("Carlos Garc.a Gonz.lez" , "Carlos Alberto García González", speeches$who)
    speeches$who <- gsub.e("^Ricardo Suárez$" , "Ricardo Astudillo Suárez", speeches$who)
    speeches$who <- gsub.e("Jorge De la Vega Membrillo" , "Jorge Federico De la Vega Membrillo", speeches$who)
    speeches$who <- gsub.e("José Francisco Cáceres De la Fuente" , "Juan Francisco Cáceres De la Fuente", speeches$who)
    speeches$who <- gsub.e("Elizabeth Yáñez Robles" , "Elizabeth Oswelia Yáñez Robles", speeches$who)
    speeches$who <- gsub.e("Mario Carrillo Huerta" , "Mario Miguel Carrillo Huerta", speeches$who)
    speeches$who <- gsub.e("Arturo Valle Magaña" , "José Luis Valle Magaña", speeches$who)
    speeches$who <- gsub.e("Francisco José Coronato Rodríguez" , "José Francisco Coronato Rodríguez", speeches$who)
    speeches$who <- gsub.e("José Antonio Sampayo Ortiz" , "Ramón Antonio Sampayo Ortiz", speeches$who)
    speeches$who <- gsub.e("María del Carmen López Segura" , "María Carmen López Segura", speeches$who)
    speeches$who <- gsub.e("Jorge Sergio Manzur Quiroga" , "José Sergio Manzur Quiroga", speeches$who)
    speeches$who <- gsub.e("Manuela Huerta Ladr.n de Guevara" , "Manuel Rafael Huerta Ladrón de Guevara", speeches$who)
    speeches$who <- gsub.e("Lis .ngel Espinosa Ch.zaro" , "Luis Angel Xariel Espinosa Cházaro", speeches$who)
    speeches$who <- gsub.e("Posadas Hernández Domitilo" , "Domitilo Posadas Hernández", speeches$who)
    speeches$who <- gsub.e("Mar[ií]a del? Roc.. Garc[íi]a Olmedo" , "María del Rocío Garcia Olmedo", speeches$who)
    speeches$who <- gsub.e("Damián Vidales Zepeda" , "Damián Zepeda Vidales", speeches$who)
    speeches$who <- gsub.e("Marcela Velázquez Sánchez" , "Maricela Velázquez Sánchez", speeches$who)
    speeches$who <- gsub.e("Eulalia Lourdes Quiñones Canales" , "Lourdes Eulalia Quiñones Canales", speeches$who)
    speeches$who <- gsub.e("Javier Azuara Zúñiga" , "Xavier Azuara Zúñiga", speeches$who)
    speeches$who <- gsub.e("Maya Guadalupe Mondragón González" , "Ma. Guadalupe Mondragón González", speeches$who)
    speeches$who <- gsub.e("Francisco Liceaga Arteaga Gerardo" , "Gerardo Francisco Liceaga Arteaga", speeches$who)
    speeches$who <- gsub.e("María Rosario Merlín García" , "María del Rosario Merlín García", speeches$who)
    speeches$who <- gsub.e("Merlín García María del Rosario" , "María del Rosario Merlín García", speeches$who)
    speeches$who <- gsub.e("María Luisa Alcalde Luján" , "Luisa María Alcalde Luján", speeches$who)
    speeches$who <- gsub.e("Víctor Manuel Díaz Palacios" , "Víctor Emanuel Díaz Palacios", speeches$who)
    speeches$who <- gsub.e("César Reynaldo Navarro De Alba" , "César Reynaldo Navarro De Alva", speeches$who)
    speeches$who <- gsub.e("Mar[ií]a de las Nieves Garc[íi]a Fern[áa]ndez" , "María de las Nieves García Fernández", speeches$who)
    speeches$who <- gsub.e("Claudia Bojórquez Javier" , "Claudia Elizabeth Bojórquez Javier", speeches$who)
    speeches$who <- gsub.e("Ang.lica Carreño Mijares" , "Angelina Carreño Mijares", speeches$who)
    speeches$who <- gsub.e("María Mónica García De la Fuente" , "Mónica García De la Fuente", speeches$who)
    speeches$who <- gsub.e("Nelly Lázara González Aguilar" , "Lázara Nelly González Aguilar", speeches$who)
    speeches$who <- gsub.e("Ramón Hernández Montalvo" , "Ramón Montalvo Hernández", speeches$who)
    speeches$who <- gsub.e("Francisco Arroyo Vieyra" , "Francisco Agustín Arroyo Vieyra", speeches$who)
    speeches$who <- gsub.e("Gabriel Eugenia Cortés Talamantes" , "Gabriela Eugenia Cortés Talamantes", speeches$who)
    speeches$who <- gsub.e("Gloria Rincón Chanona" , "Sonia Rincón Chanona", speeches$who)
    speeches$who <- gsub.e("Miguel Alfonso Vildosola Lacarra" , "Miguel Vildosola Lacarra", speeches$who)
    speeches$who <- gsub.e("María Dolores García Medina" , "Amalia Dolores García Medina", speeches$who)
    speeches$who <- gsub.e("Víctor Fuentes Sol[ií]s" , "Víctor Oswaldo Fuentes Solís", speeches$who)


